### ISSUE TITLE
Looking forward to the open source code!

### ISSUE THREAD

**Issue by s0219** [Winfredy/SadTalker#1]

**Comment by HuiFHub** [comment]
When to release the code？Thanks.

**Comment by vinthony** [comment]
Hi, thanks for your attention! we will release all the code around next month~(3.1).

**Comment by MaxMax2016** [comment]
When to release the code？Thanks.

**Comment by aishoot** [comment]
Nice work!  +1

**Comment by vinthony** [comment]
Dear all, thanks for your attention and patience, the inference code of our paper has been publicly available! 

Have fun!

**Comment by anwoflow** [comment]
> 

thanks a lot, great effort! Really can't wait to check out your work. 
Could you just check the permissions on the pre-trained model folder? Getting "You need access" at the moment.

**Comment by vinthony** [comment]
fixed
