### ISSUE TITLE
关于启动参数与3D openpose editer插件冲突的问题

### ISSUE THREAD

**Issue by one0oneChen** [Winfredy/SadTalker#108]
windows中的stable diffusion 当webui-user.bat 增加了启动参数 --no-gradio-queue  和 --disable-safe-unpickle, 会导致3D Openpose插件的编辑视图不可见的错误, 希望能优化一下代码, 把这两个启动参数去掉, 不加入  --no-gradio-queue 这个启动参数可以解决3D openpose插件的视图不可见问题, --disable-safe-unpickle 仍然会导致一些其他bug

**Comment by vinthony** [comment]
其实只需要`--disable-safe-unpickle`, 这个问题会在近期更新

**Comment by vinthony** [comment]
fixed
