### ISSUE TITLE
How to run SadTalker in stable-diffusion-web-ui?

### ISSUE THREAD

**Issue by D-Mad** [Winfredy/SadTalker#11]
Thank you for your work on SadTalker! Could you please provide instructions on how to run SadTalker in stable-diffusion-web-ui?

**Comment by vinthony** [comment]
sd-webui is still tuning. We provide a [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Winfredy/SadTalker/blob/main/quick_demo.ipynb) demo, where you can play it online.

**Comment by johndpope** [comment]
you may find this helpful as a basis point - 
https://rentry.org/sd-loopback-wave

https://www.tiktok.com/@aicatgirls/video/7212864658166861102

**Comment by vinthony** [comment]
Add sd-extension.  Just install it in extensions -> install from URL -> https://github.com/Winfredy/SadTalker, which may take several minutes to download the models automatically.

**Comment by johndpope** [comment]
nice

**Comment by klarrieu** [comment]
> Add sd-extension. Just install it in extensions -> install from URL -> https://github.com/Winfredy/SadTalker, which may take several minutes to download the models automatically.

Maybe a noob question, but I tried this (using the standard python venv from sd-webui) but am getting an error with the package versions: 

```ImportError: Numba needs NumPy 1.21 or less```

I haven't been able to figure out how to downgrade numpy in the venv without breaking things. Any help appreciated!
