### ISSUE TITLE
ModuleNotFoundError: No module named 'ai'

### ISSUE THREAD

**Issue by xueli2015** [Winfredy/SadTalker#113]
setup share=Ture

> app.py
> if __name__ == "__main__":
> 
>     demo = sadtalker_demo()
>     demo.launch(share=True)

after click generate button

> Traceback (most recent call last):
>   File "/workspace/anaconda3/envs/sadtalker/lib/python3.8/site-packages/gradio/routes.py", line 395, in run_predict
>     output = await app.get_blocks().process_api(
>   File "/workspace/anaconda3/envs/sadtalker/lib/python3.8/site-packages/gradio/blocks.py", line 1193, in process_api
>     result = await self.call_function(
>   File "/workspace/anaconda3/envs/sadtalker/lib/python3.8/site-packages/gradio/blocks.py", line 916, in call_function
>     prediction = await anyio.to_thread.run_sync(
>   File "/workspace/anaconda3/envs/sadtalker/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "/workspace/anaconda3/envs/sadtalker/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
>     return await future
>   File "/workspace/anaconda3/envs/sadtalker/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
>     result = context.run(func, *args)
>   File "/workspace/SadTalker/src/gradio_demo.py", line 64, in test
>     self.preprocess_model = CropAndExtract(self.path_of_lm_croper, self.path_of_net_recon_model, self.dir_of_BFM_fitting, self.device)
>   File "/workspace/SadTalker/src/utils/preprocess.py", line 48, in __init__
>     checkpoint = torch.load(path_of_net_recon_model, map_location=torch.device(device))
>   File "/workspace/anaconda3/envs/sadtalker/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
>     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>   File "/workspace/anaconda3/envs/sadtalker/lib/python3.8/site-packages/torch/serialization.py", line 930, in _legacy_load
>     result = unpickler.load()
>   File "/workspace/anaconda3/envs/sadtalker/lib/python3.8/site-packages/torch/serialization.py", line 746, in find_class
>     return super().find_class(mod_name, name)
> ModuleNotFoundError: No module named 'ai'

**Comment by vinthony** [comment]
are you using the latest version?

**Comment by vinthony** [comment]
it seems to be duplicated with https://github.com/Winfredy/SadTalker/issues/167, please refer to that issue. closed this one, if you have any problem please reopen it.
