### ISSUE TITLE
minimum vram requirements?

### ISSUE THREAD

**Issue by gsgoldma** [Winfredy/SadTalker#118]
trying at 6 gigs vram
it loads some of it, then I get an OOM error

D:\stable-diffusion-webui\models\sadtalker\shape_predictor_68_face_landmarks.dat███████| 20/20 [00:16<00:00,  1.65it/s]
D:\stable-diffusion-webui\models\sadtalker\auido2pose_00140-model.pth
D:\stable-diffusion-webui\models\sadtalker\facevid2vid_00189-model.pth.tar
C:\Users\Gregory\AppData\Local\Temp\tmpzliw9ldq.png
landmark Det:: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:09<00:00,  9.52s/it]
3DMM Extraction In Video:: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.51it/s]
mel:: 100%|█████████████████████████████████████████████████████████████████████████| 89/89 [00:00<00:00, 44313.04it/s]
audio2exp:: 100%|████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 81.08it/s]
Face Renderer::   0%|                                                                           | 0/45 [00:05<?, ?it/s]

**Comment by vinthony** [comment]
8GM may be fine. or you can manually change the `--batch_size` to 1

**Comment by vinthony** [comment]
close since no long-time update.

**Comment by vinthony** [comment]
refer to: https://github.com/Winfredy/SadTalker/issues/124#issuecomment-1508113989
