### ISSUE TITLE
extract_kp_videos.py中读取图片关键点时索引超出界限

### ISSUE THREAD

**Issue by Gltton** [Winfredy/SadTalker#12]
第33行 keypoints.append(current_kp[-1])  报错 list index out of range ，请问一下这是我的素材的问题吗

**Comment by Winfredy** [comment]
可以提供一下你的source image吗 我运行一下试试

**Comment by Gltton** [comment]
我是在[video-retalking](https://github.com/vinthony/video-retalking)这个项目里面运行的时候报的这个错误用的就是提供的例子，显示是在这个模块出现的问题我看一下代码是一样的想问下问题在那里
