### ISSUE TITLE
pose style [0, 46)

### ISSUE THREAD

**Issue by cmmclee** [Winfredy/SadTalker#120]
pose style [0, 46) 的依据是什么？是不是由46个driving video对应生成的？

**Comment by vinthony** [comment]
训练集中的46个id

**Comment by hokamc** [comment]
will there be any example for each pose style? like the difference between them

**Comment by vinthony** [comment]
you can find it in our project page

**Comment by tenghuil** [comment]
Can you give a link? I didn't see which value maps to which pose from the project page

**Comment by luyao-cv** [comment]
how can get the link?
