### ISSUE TITLE
LOGO有参数可以控制显示隐藏么？

### ISSUE THREAD

**Issue by skyeKing** [Winfredy/SadTalker#121]
如题

**Comment by CeterPushing** [comment]
Browse to stable-diffusion-webui/extensions/SadTalker/src/utils/ and open paste_pic.py

near the bottom of the paste_pic function, you should see the following line of code:

    save_video_with_watermark(tmp_path, new_audio_path, full_video_path, watermark=True)
Replace the True at the end with False:
    save_video_with_watermark(tmp_path, new_audio_path, full_video_path, watermark=False)

Save the file, and restart the automatic1111 backend if it was running. After that, the generated videos won't have a watermark anymore.

Google Translate:

浏览到 stable-diffusion-webui/extensions/SadTalker/src/utils/ 并打开 paste_pic.py

在 paste_pic 函数的底部附近，您应该看到以下代码行：

     save_video_with_watermark(tmp_path, new_audio_path, full_video_path, watermark=True)
将末尾的 True 替换为 False：
     save_video_with_watermark(tmp_path, new_audio_path, full_video_path, watermark=False)

保存文件，并重新启动 automatic1111 后端（如果它正在运行）。 之后，生成的视频将不再有水印。
