### ISSUE TITLE
colab error in release v0.0.2

### ISSUE THREAD

**Issue by jiedong-yang** [Winfredy/SadTalker#125]
Hi everyone,

I tried to run this on colab, but run into the error below. I can get it running by copy the checkpoint to the location
```
%mkdir -p /root/.cache/torch/hub/checkpoints/
%cp /content/SadTalker/checkpoints/hub/checkpoints/s3fd-619a316812.pth /root/.cache/torch/hub/checkpoints/s3fd-619a316812.pth
```

Anyway to fix this in code? Thanks!

```
examples/source_image/full3.png
./checkpoints/epoch_20.pth
Traceback (most recent call last):
  File "inference.py", line 158, in <module>
    main(args)
  File "inference.py", line 55, in main
    preprocess_model = CropAndExtract(path_of_lm_croper, path_of_net_recon_model, dir_of_BFM_fitting, device)
  File "/content/SadTalker/src/utils/preprocess.py", line 51, in __init__
    self.kp_extractor = KeypointExtractor(device)
  File "/content/SadTalker/src/face3d/extract_kp_videos.py", line 16, in __init__
    self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, 
  File "/usr/local/lib/python3.8/dist-packages/face_alignment/api.py", line 77, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose, **face_detector_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/face_alignment/detection/sfd/sfd_detector.py", line 26, in __init__
    model_weights = torch.load(path_to_detector)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/torch/hub/checkpoints/s3fd-619a316812.pth'
```

**Comment by jiedong-yang** [comment]
I think I located the error. In the new update of [src/face3d/extract_kp_videos.py](https://github.com/Winfredy/SadTalker/blob/main/src/face3d/extract_kp_videos.py), the init method has been updated to 
`python
def __init__(self, device):
        self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, 
                                                     face_detector_kwargs={"path_to_detector":"/root/.cache/torch/hub/checkpoints/s3fd-619a316812.pth"},
                                                     device=device)
`

**Comment by emmajane1313** [comment]
im getting the same error when i try to run in colab also

**Comment by emmajane1313** [comment]
hey, just solved after the Sadtalker repo has installed go into the sadtalker folder and navigate to `src/face3d/extract_key_videos.py` and open the file and edit line 17 to change the path from `"/root/.cache/torch/hub/checkpoints/s3fd-619a316812.pth"` to `"/content/SadTalker/checkpoints/hub/checkpoints/s3fd-619a316812.pth"`

then you can run the rest of the cells normally and it should work :)

**Comment by vinthony** [comment]
Sorry for this when I debug on my computer. fixed now.

**Comment by Ionaut** [comment]
Slashes were backwards. I needed: D:\SadTalker\checkpoints\hub\checkpoints\s3fd-619a316812.pth on windows

**Comment by jiedong-yang** [comment]
> 

Thank you for taking the time to look at it! Appreciated!
