### ISSUE TITLE
Illegal Hardware Error: Mac M1

### ISSUE THREAD

**Issue by emmajane1313** [Winfredy/SadTalker#129]
SD A1111 is crashing when I install the sad talker library on my mac m1 with this error:

```
[1]    53170 illegal hardware instruction  ./webui.sh --disable-safe-unpickle
/Users/devdesign/.asdf/installs/python/3.10.1/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

SD works fine without sad talker but it seems the extension is not compatible with m1? I'm running the SD webui with the `--disable-safe-unpickle` flag

**Comment by vinthony** [comment]
In `extensions/Sadtalker/scripts/extension.py`, replace `dlib-bin` to `dlib`

![image](https://user-images.githubusercontent.com/4397546/231660155-cb22fd75-72f0-4af8-b696-865d0c474ded.png)

**Comment by vinthony** [comment]
we have solve the problem of M1 installation in https://github.com/Winfredy/SadTalker/commit/0c3649b88a14663cda779f81663b0694a118693b, close this one and let me know if you have any problem.

**Comment by emmajane1313** [comment]
I tried that but unfortunately am still getting this 
`[1]    75040 illegal hardware instruction  ./webui.sh`
