### ISSUE TITLE
图片生成的视频分辨率如何提高？怎么样设置生成的视频不是只有人头

### ISSUE THREAD

**Issue by magicleo** [Winfredy/SadTalker#13]
hi
请问基于图片生成的视频分辨率如何提高？
怎么样设置生成的视频不是只有人头，能够包含原图片全身型像？

**Comment by Winfredy** [comment]
可以采用[GFPGAN](https://github.com/TencentARC/GFPGAN)来提高生成视频的分辨率。
我们尝试过将生成的视频贴回到原图像上，但会存在边缘处无法对齐现象，目前还在尝试改善这一问题，后续有进展会继续更新代码

**Comment by magicleo** [comment]
@Winfredy  感谢回复，对于视频图像大小，有没有参数能将图片改的稍微大一点，哪怕不是完全的原图，也从原图裁剪更大的区域出来

**Comment by Hothin** [comment]
> 可以采用[GFPGAN](https://github.com/TencentARC/GFPGAN)来提高生成视频的分辨率。 我们尝试过将生成的视频贴回到原图像上，但会存在边缘处无法对齐现象，目前还在尝试改善这一问题，后续有进展会继续更新代码

请问对于边缘处无法对齐这个问题，你们有什么解决的思路嘛

**Comment by magicleo** [comment]
> 可以采用[GFPGAN](https://github.com/TencentARC/GFPGAN)来提高生成视频的分辨率。 我们尝试过将生成的视频贴回到原图像上，但会存在边缘处无法对齐现象，目前还在尝试改善这一问题，后续有进展会继续更新代码

感谢回复，请问对问题2，有什么现在能做的折中办法吗？

**Comment by vinthony** [comment]
> > 可以采用[GFPGAN](https://github.com/TencentARC/GFPGAN)来提高生成视频的分辨率。 我们尝试过将生成的视频贴回到原图像上，但会存在边缘处无法对齐现象，目前还在尝试改善这一问题，后续有进展会继续更新代码
> 
> 感谢回复，请问对问题2，有什么现在能做的折中办法吗？

GFPGAN已经official的加入了， 问题2目前还没有哈。

**Comment by 2793145003** [comment]
> 

用把脸和头发分割出来之后和原图做seamlessClone，相对没有违和感。
分割参考：https://github.com/YudongGuo/AD-NeRF/blob/master/data_util/face_parsing/test.py

**Comment by yujack333** [comment]
> 2793145003

非常好的想法，请问有效果可以看看吗？
