### ISSUE TITLE
[SOLVED] i have the wav2lip.pth in the correct folder but it refuses to see it

### ISSUE THREAD

**Issue by Vincevinny** [Winfredy/SadTalker#134]
Edit: i was able to solve it by adjusting the web user.bat path to the checkpoints i was using a copy paste of this from the main page "set SADTALKER_CHECKPOINTS=D:\SadTalker\checkpoints" but my install path was different, leaving this up to help other noobs

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\SadTalker\\checkpoints\\wav2lip.pth'

**Comment by vinthony** [comment]
close it since it has been solved

**Comment by roadev** [comment]
> close it since it has been solved

How did you solve it?

**Comment by Vincevinny** [comment]
> > close it since it has been solved
> 
> How did you solve it?

so the default command "set SADTALKER_CHECKPOINTS=D:\SadTalker\checkpoints" did not point to my actual folders 
mine was something like E:\Stable Diffusion WebUI\stable-diffusion-webui-1.1.0\extensions... ect  i merely updated the instruction in the bat to reflect the actual location of the sadtalker files on my pc
