### ISSUE TITLE
Can we please get rid of the watermark?

### ISSUE THREAD

**Issue by bbecausereasonss** [Winfredy/SadTalker#136]
Everyone here knows how to manually get rid of it, it's just a nuisance at this point.

**Comment by Fy-** [comment]
You can just remplace` /extensions/SadTalker/docs/sadtalker_logo.png` for sd web ui or `/../../docs/sadtalker_logo.png` with a transparent png or replace line 25  in src/utils/videoio.py by   ` if True:`
