### ISSUE TITLE
最新版source_image参数不支持视频吗？

### ISSUE THREAD

**Issue by sauces88** [Winfredy/SadTalker#138]
AttributeError: 'NoneType' object has no attribute 'shape'， http://mapi.jyaigc.com/91app/2023/04/12/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20230412180653.png

**Comment by zengxiang1** [comment]
> AttributeError: 'NoneType' object has no attribute 'shape'， http://mapi.jyaigc.com/91app/2023/04/12/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20230412180653.png

对的。我也碰到了。你不用full参数可以

**Comment by sauces88** [comment]
之前的版本我已经用过了，生成出来的视频只有头部，我现在用新版是想弄全身的视频...所以必须要这个参数

**Comment by sauces88** [comment]
> > AttributeError: 'NoneType' object has no attribute 'shape'， http://mapi.jyaigc.com/91app/2023/04/12/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20230412180653.png
> 
> 对的。我也碰到了。你不用full参数可以



> > AttributeError: 'NoneType' object has no attribute 'shape'， http://mapi.jyaigc.com/91app/2023/04/12/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20230412180653.png
> 
> 对的。我也碰到了。你不用full参数可以


之前的版本我已经用过了，生成出来的视频只有头部，我现在用新版是想弄全身的视频，所以必须要这个参数

**Comment by sauces88** [comment]
> > AttributeError: 'NoneType' object has no attribute 'shape'， http://mapi.jyaigc.com/91app/2023/04/12/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20230412180653.png
> 
> 对的。我也碰到了。你不用full参数可以

之前的版本我已经用过了，生成出来的视频只有头部，我现在用新版是想弄全身的视频，所以必须要这个参数

**Comment by Winfredy** [comment]
> 

这个bug已经修复了 你可以更新一下代码尝试一下

**Comment by sauces88** [comment]
> Referenc

好像还是不行，cv2.imread(pic_path)读取视频还是None

**Comment by sauces88** [comment]
之前用的3060tiG6X，换成4090后就可以了
