### ISSUE TITLE
> 这个是huggingface_hub 的版本问题，确定第48行：

### ISSUE THREAD

**Issue by wukenny11111** [Winfredy/SadTalker#141]
> 这个是huggingface_hub 的版本问题，确定第48行：
> 
> ```
> "huggingface_hub":"huggingface_hub==0.13.4",
> ```

代码这里没有问题，我这里是
 "huggingface_hub":"huggingface_hub==0.13.4",

![image](https://user-images.githubusercontent.com/130638942/231684022-5fcba495-7d8a-436d-b906-1e992b836313.png)
相关模型的目录

_Originally posted by @wukenny11111 in https://github.com/Winfredy/SadTalker/issues/123#issuecomment-1506453801_
            

再提供一个信息我用的SD是国内人做的懒人包

**Comment by vinthony** [comment]
可以提供一下信息，我自己装一下看看

**Comment by wukenny11111** [comment]
> 可以提供一下信息，我自己装一下看看

链接：https://pan.baidu.com/s/1WqzH91jNPrggspAsj9NVaw?pwd=o36j 
提取码：o36j

**Comment by wukenny11111** [comment]
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
Installing requirements for Web UI

Launching Web UI with arguments: --xformers --no-half --autolaunch --api
[AddNet] Updating model hashes...

[AddNet] Updating model hashes...

Loading weights [fc2511737a] from D:\AI\novelai-webui-aki-v3\models\Stable-diffusion\chilloutmix_NiPrunedFp32Fix.safetensors
Creating model from config: D:\AI\novelai-webui-aki-v3\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 3.1s (create model: 0.5s, apply weights to model: 0.8s, move model to device: 0.7s, load textual inversion embeddings: 1.0s).
face-alignment False
Installing requirements for SadTalker
imageio-ffmpeg False
Installing requirements for SadTalker
pyyaml False
Installing requirements for SadTalker
Found existing installation: huggingface-hub 0.13.4
Uninstalling huggingface-hub-0.13.4:
  Successfully uninstalled huggingface-hub-0.13.4
Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple, https://pypi.tuna.tsinghua.edu.cn/simple, https://pypi.doubanio.com/simple
Looking in links: https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html
Collecting git+https://github.com/huggingface/huggingface_hub@main
  Cloning https://github.com/huggingface/huggingface_hub (to revision main) to c:\users\administrator\appdata\local\temp\2\pip-req-build-ujfson1x
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/huggingface_hub 'C:\Users\Administrator\AppData\Local\Temp\2\pip-req-build-ujfson1x'
  fatal: unable to access 'https://github.com/huggingface/huggingface_hub/': Failed to connect to github.com port 443 after 21065 ms: Timed out
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/huggingface/huggingface_hub 'C:\Users\Administrator\AppData\Local\Temp\2\pip-req-build-ujfson1x' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/huggingface/huggingface_hub 'C:\Users\Administrator\AppData\Local\Temp\2\pip-req-build-ujfson1x' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Error executing callback ui_tabs_callback for D:\AI\novelai-webui-aki-v3\extensions\SadTalker\scripts\extension.py
Traceback (most recent call last):
  File "D:\AI\novelai-webui-aki-v3\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "D:\AI\novelai-webui-aki-v3\extensions\SadTalker\scripts\extension.py", line 74, in on_ui_tabs
    install()
  File "D:\AI\novelai-webui-aki-v3\extensions\SadTalker\scripts\extension.py", line 65, in install
    launch.run(f'"{python}" -m pip install --upgrade git+https://github.com/huggingface/huggingface_hub@main', live=True)
  File "D:\AI\novelai-webui-aki-v3\launch.py", line 97, in run
    raise RuntimeError(f"""{errdesc or 'Error running command'}.
RuntimeError: Error running command.
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Command: "D:\AI\novelai-webui-aki-v3\py310\python.exe" -m pip install --upgrade git+https://github.com/huggingface/huggingface_hub@main
Error code: 1




更新最新版本后的一个报错

**Comment by vinthony** [comment]
这个应该是网络问题，看起来连接不到github

**Comment by wukenny11111** [comment]
> 这个应该是网络问题，看起来连接不到github

不知道相关文件是否可以在墙内提供一份？

**Comment by vinthony** [comment]
可以follow一下最新的文档：https://github.com/Winfredy/SadTalker/blob/main/docs/webui_extension.md

**Comment by vinthony** [comment]
这里也有一个百度云盘： https://github.com/Winfredy/SadTalker/issues/143

**Comment by wukenny11111** [comment]
> 这里也有一个百度云盘： #143

已经正常安装了，感谢支持！加油！！

**Comment by vinthony** [comment]
enjoy：）
