### ISSUE TITLE
re-install requirements every time I open automatic1111

### ISSUE THREAD

**Issue by ffiras** [Winfredy/SadTalker#146]
Every time I open automatic1111 web UI it will re-install all requirements and re-dowload the models again.

**Comment by Luvdraft** [comment]
The same problem!

**Comment by ffiras** [comment]
I just commented the line 69 "install()" function under SadTalker\scripts\extention.py file for now.

**Comment by amiremami** [comment]
Same problem on windows. What's the solution?

**Comment by an303042** [comment]
Add 
`set SADTALKER_CHECKPOINTS=.\extensions\SadTalker\checkpoints`
to webui-user.bat

**Comment by bbecausereasonss** [comment]
I already have a set checkpoints in user-webui, but I need it to stop doing that in webui.

**Comment by vinthony** [comment]
Hi, we have updated the code to prevent auto-installation and make sure you have set the path of the checkpoint.

**Comment by vinthony** [comment]
fixed this issue in the latest version. reopen it if you have any problem with reinstall requirements.

**Comment by daarkwulf** [comment]
Should we still have to add path to checkpoints ? Can someone tell me how to add it and where ?
