### ISSUE TITLE
Having problems running sadtalker extension

### ISSUE THREAD

**Issue by an303042** [Winfredy/SadTalker#148]
Hey,
So tried running it, this is what he console looks like - 

Loading CLiP model ViT-L/14 ███████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  3.49it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:14<00:00,  1.38it/s]
.\extensions\SadTalker\checkpoints\auido2pose_00140-model.pth██████████████████████████| 20/20 [00:14<00:00,  3.49it/s]
.\extensions\SadTalker\checkpoints\shape_predictor_68_face_landmarks.dat
.\extensions\SadTalker\checkpoints\facevid2vid_00189-model.pth.tar
C:\Users\USER\AppData\Local\Temp\tmp52guspxg.png
landmark Det:: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.53s/it]
3DMM Extraction In Video:: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.56it/s]
mel:: 100%|████████████████████████████████████████████████████████████████████████| 93/93 [00:00<00:00, 185836.24it/s]
audio2exp:: 100%|██████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 56.50it/s]
Face Renderer:: 100%|██████████████████████████████████████████████████████████████████| 47/47 [00:16<00:00,  2.77it/s]
Traceback (most recent call last):
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\SD\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "F:\SD\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 122, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess)
  File "F:\SD\stable-diffusion-webui/extensions/SadTalker\src\facerender\animate.py", line 176, in generate
    sound = AudioSegment.from_mp3(audio_path)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\pydub\audio_segment.py", line 796, in from_mp3
    return cls.from_file(file, 'mp3', parameters=parameters)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\pydub\audio_segment.py", line 773, in from_file
    raise CouldntDecodeError(
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

Output from ffmpeg/avlib:

ffmpeg version 5.1.2-essentials_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[mp3float @ 000001bae0a5a1c0] Header missing
    Last message repeated 102 times
[mp3 @ 000001bae0a50f00] Could not find codec parameters for stream 0 (Audio: mp3 (mp3float), 0 channels, fltp): unspecified frame size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, mp3, from 'F:\SD\stable-diffusion-webui\outputs\SadTalker\d5e43f5e-01c8-4473-acfd-d1ad308a8cdc\input\NewRecording7-0-100.m4a':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Audio: mp3, 0 channels, fltp
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (mp3float) -> pcm_s16le (native))
Press [q] to stop, [?] for help
[mp3float @ 000001bae0a4be80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001bae0a4be80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001bae0a4be80] Header missing

.
.
.
Any ideas for me?
TIA

**Comment by vinthony** [comment]
are you using mp3 or wag audio?

**Comment by an303042** [comment]
Thank you! its was m4a. Works fine once converted to mp3
