### ISSUE TITLE
SD-WEBUI从网址无法安装？

### ISSUE THREAD

**Issue by paulzhang913** [Winfredy/SadTalker#149]
GitCommandError: Cmd('git') failed due to: exit code(128) cmdline: git clone -v -- https://github.com/Winfredy/SadTalker C:\softz\tmp\SadTalker stderr: 'Cloning into 'C:\softz\tmp\SadTalker'... fatal: unable to access 'https://github.com/Winfredy/SadTalker/': Failed to connect to github.com port 443 after 21051 ms: Timed out '

**Comment by wukenny11111** [comment]
> GitCommandError: Cmd('git') failed due to: exit code(128) cmdline: git clone -v -- https://github.com/Winfredy/SadTalker C:\softz\tmp\SadTalker stderr: 'Cloning into 'C:\softz\tmp\SadTalker'... fatal: unable to access 'https://github.com/Winfredy/SadTalker/': Failed to connect to github.com port 443 after 21051 ms: Timed out '

你这个是网络问题，无法连接到git导致的

**Comment by vinthony** [comment]
refer: https://github.com/Winfredy/SadTalker/issues/143
