### ISSUE TITLE
How can I stop it auto-installing?

### ISSUE THREAD

**Issue by bbecausereasonss** [Winfredy/SadTalker#150]
My installation from webui.bat keeps failing... I need to get into web ui without arguments to manage my extensions, but with Sadtalker in place it freezes my process.

What do I have to edit to tell Sadtalker it installed correctly?

LAB
face-alignment False
Installing requirements for SadTalker
imageio True
imageio-ffmpeg False
Installing requirements for SadTalker
librosa True
pydub True
scipy True
tqdm True
yacs True
pyyaml False
Installing requirements for SadTalker
dlib True
gfpgan True
Fetching 22 files:   0%|                                                                        | 0/22 [00:00<?, ?it/s]

**Comment by vinthony** [comment]
see #146

**Comment by vinthony** [comment]
fixed in the latest version and duplicated with #146
