### ISSUE TITLE
人脸识别不准确

### ISSUE THREAD

**Issue by stormcenter** [Winfredy/SadTalker#154]
/src/utils/preprocess.py 56行，pic_size = 256会导致有些图片识别不出来比如：附件里的这张图，识别后，被裁剪成这样了。
如果改成pic_size=512就可以正常识别。
![1681227702](https://user-images.githubusercontent.com/3783795/231926259-4c3d21b8-a522-434f-b0bd-b7539a1a83c7.jpg)
![crop1](https://user-images.githubusercontent.com/3783795/231926288-178eff7f-2e97-4dee-9bdc-53fd8ac2b28b.jpg)

**Comment by vinthony** [comment]
Thanks for your contribution. fixed.
