### ISSUE TITLE
--preprocess resize 或 full 报错

### ISSUE THREAD

**Issue by DogeFlow** [Winfredy/SadTalker#155]
如题，报错如下：
![image](https://user-images.githubusercontent.com/34650487/231962816-a992c14e-1369-4e40-a53b-299a93a4dd84.png)

**Comment by DogeFlow** [comment]
> 

在src/utils/preprocess.py中，line 92，少了个逗号吧
crop_info = ((ox2 - ox1, oy2 - oy1),)

**Comment by vinthony** [comment]
请使用最新版本：）

https://github.com/Winfredy/SadTalker/blob/84d1f4eb5eabb9a6a02d2f8766e618b4a2812715/src/utils/preprocess.py#L107

**Comment by DogeFlow** [comment]
> 请使用最新版本：）
> 
> https://github.com/Winfredy/SadTalker/blob/84d1f4eb5eabb9a6a02d2f8766e618b4a2812715/src/utils/preprocess.py#L107

thank you
