### ISSUE TITLE
--preprocess full无法使用

### ISSUE THREAD

**Issue by DogeFlow** [Winfredy/SadTalker#156]
inference.py: error: argument --preprocess: invalid choice: 'full' (choose from 'crop', 'resize')

**Comment by vinthony** [comment]
https://github.com/Winfredy/SadTalker/blob/84d1f4eb5eabb9a6a02d2f8766e618b4a2812715/inference.py#L135

are you using the latest version?

**Comment by DogeFlow** [comment]
> https://github.com/Winfredy/SadTalker/blob/84d1f4eb5eabb9a6a02d2f8766e618b4a2812715/inference.py#L135
> 
> are you using the latest version?

thank you
