### ISSUE TITLE
在SD中还有一些小异常，麻烦看一下

### ISSUE THREAD

**Issue by wukenny11111** [Winfredy/SadTalker#161]
The generated video is named D:\AI\novelai-webui-aki-v3\outputs\SadTalker\b8a9a619-a1c4-4dea-8010-98a885808537/tmp7g1jeedy##14g2x3glv_enhanced.mp4
The generated video is named tmp7g1jeedy##14g2x3glv in D:\AI\novelai-webui-aki-v3\outputs\SadTalker\b8a9a619-a1c4-4dea-8010-98a885808537
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 162, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 162, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by vinthony** [comment]
国内网络问题，我晚上更新一个指南来离线使用

**Comment by wukenny11111** [comment]
> 更新

感谢！加油！

**Comment by wukenny11111** [comment]
> 国内网络问题，我晚上更新一个指南来离线使用

另外，我用conda部署了一套，想请教下，有关视频分辨率和码率的问题，不知道可以吗？

**Comment by vinthony** [comment]
> > 国内网络问题，我晚上更新一个指南来离线使用
> 
> 另外，我用conda部署了一套，想请教下，有关视频分辨率和码率的问题，不知道可以吗？

我们目前采用的是网络256x256，使用gfpgan超分的思路去做。512的模型可能后续才会训练。

**Comment by vinthony** [comment]
> > 更新
> 
> 感谢！加油！

之前看错了，这个好像不是网络的问题，好像是sdwebui的bug，https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7524

**Comment by wukenny11111** [comment]
> > > 国内网络问题，我晚上更新一个指南来离线使用
> > 
> > 
> > 另外，我用conda部署了一套，想请教下，有关视频分辨率和码率的问题，不知道可以吗？
> 
> 我们目前采用的是网络256x256，使用gfpgan超分的思路去做。512的模型可能后续才会训练。

后面用512模型了是不是视频的视频分辨率，码率可以一次性做的比较高了？而不是现在一点点超分处理？

**Comment by vinthony** [comment]
是的。后续如果驱动网络训练比较ok可以不用超分。这个issue我关闭了。

**Comment by ugooai** [comment]
> > > 更新
> > 
> > 
> > 感谢！加油！
> 
> 之前看错了，这个好像不是网络的问题，好像是sdwebui的bug，[AUTOMATIC1111/stable-diffusion-webui#7524](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7524)

我是独立部署的，没有在SD中安装，也有这个问题

**Comment by yang1010x** [comment]
把asyncio\windows_events.py里面的

DefaultEventLoopPolicy = WindowsProactorEventLoopPolicy
改成

DefaultEventLoopPolicy = WindowsSelectorEventLoopPolicy
