### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by doniedarkos** [Winfredy/SadTalker#164]
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\AI/extensions/SadTalker/checkpoints/wav2lip.pth'
I don't have a folder with this name "checkpoints" and the file does not exist "wav2lip.pth"c?

**Comment by vinthony** [comment]
https://github.com/Winfredy/SadTalker/blob/main/docs/webui_extension.md please download the checkpoint and put it in the right location

**Comment by doniedarkos** [comment]
Thank you!

**Comment by vinthony** [comment]
closed since it has been solved
