### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by ubohex** [Winfredy/SadTalker#172]
E:\Stable-diffusion\extensions\SadTalker\checkpoints\auido2pose_00140-model.pth
E:\Stable-diffusion\extensions\SadTalker\checkpoints\shape_predictor_68_face_landmarks.dat
E:\Stable-diffusion\extensions\SadTalker\checkpoints\facevid2vid_00189-model.pth.tar
E:\stable-diffusion\tmp\tmp85wtzpya.png
landmark Det:: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:06<00:00,  6.27s/it]
3DMM Extraction In Video:: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.09it/s]
mel:: 100%|█████████████████████████████████████████████████████████████████████████| 56/56 [00:00<00:00, 55292.14it/s]
audio2exp:: 100%|████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 95.27it/s]
Face Renderer:: 100%|██████████████████████████████████████████████████████████████████| 28/28 [00:09<00:00,  2.81it/s]
"ffmpeg" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
Traceback (most recent call last):
  File "E:\Stable-diffusion\python\lib\shutil.py", line 815, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] Не удается найти указанный файл: '2f7b2de6-95e1-49d0-ba29-81db49e94ce2.mp4' -> 'E:\\Stable-diffusion\\outputs\\SadTalker\\8b76a621-ffb2-442c-9286-4ffbf22e2ec0\\tmp85wtzpya##Hello how are you -0-100.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\stable-diffusion\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\stable-diffusion\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "E:\stable-diffusion\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\stable-diffusion\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\stable-diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\stable-diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Stable-diffusion\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "E:\Stable-diffusion/extensions/SadTalker\src\gradio_demo.py", line 122, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess)
  File "E:\Stable-diffusion/extensions/SadTalker\src\facerender\animate.py", line 183, in generate
    save_video_with_watermark(path, new_audio_path, av_path, watermark= False)
  File "E:\Stable-diffusion/extensions/SadTalker\src\utils\videoio.py", line 26, in save_video_with_watermark
    shutil.move(temp_file, save_path)
  File "E:\Stable-diffusion\python\lib\shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "E:\Stable-diffusion\python\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "E:\Stable-diffusion\python\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '2f7b2de6-95e1-49d0-ba29-81db49e94ce2.mp4'

**Comment by vinthony** [comment]
please insure ffmpeg is installed and in the %PATH% of your computer, refer this: https://github.com/Winfredy/SadTalker/blob/main/docs/install.md#windows-native

**Comment by ubohex** [comment]
ffmpeg alredy installed:
C:\Windows\system32>ffmpeg -version
ffmpeg version 2023-04-12-git-1179bb703e-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil      58.  6.100 / 58.  6.100
libavcodec     60.  9.100 / 60.  9.100
libavformat    60.  4.101 / 60.  4.101
libavdevice    60.  2.100 / 60.  2.100
libavfilter     9.  5.100 /  9.  5.100
libswscale      7.  2.100 /  7.  2.100
libswresample   4. 11.100 /  4. 11.100
libpostproc    57.  2.100 / 57.  2.100

But problem is still here:
FileNotFoundError: [Errno 2] No such file or directory: '2a9c8ffc-3525-4154-af94-b7aa567d4786.mp4'

**Comment by ubohex** [comment]
+ if I press the "load From text2img" button, have this error:
Traceback (most recent call last):
  File "E:\stable-diffusion\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\stable-diffusion\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "E:\stable-diffusion\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\stable-diffusion\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\stable-diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\stable-diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Stable-diffusion\extensions\SadTalker\scripts\extension.py", line 52, in get_img_from_txt2img
    img_from_txt_path = os.path.join(imgs_from_txt_dir, imgs[-1])
IndexError: list index out of range

**Comment by vinthony** [comment]
it seems you do not have an image in text2image tab?

**Comment by ubohex** [comment]
![2023-4-16 11-2-36](https://user-images.githubusercontent.com/52637962/232283708-17723c21-5e60-4ab8-bd91-db0671751b97.png)
![2023-4-16 11-2-54](https://user-images.githubusercontent.com/52637962/232283711-224f2331-387c-4573-8901-d1fb3c5eb48e.png)

**Comment by vinthony** [comment]
please try to refresh the WebUI. Are you change the output of text2image?

**Comment by ubohex** [comment]
refreshed, updated, rebooted, but that's not the main problem! I can load a picture from my saved ones. 
**The main problem is this:**
Traceback (most recent call last):
  File "E:\Stable-diffusion\python\lib\shutil.py", line 815, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] Не удается найти указанный файл: 'd3e190da-e0b7-4488-aef7-d9e1be1f6850.mp4' -> 'E:\\Stable-diffusion\\outputs\\SadTalker\\db886a54-6317-4e8c-baaf-ab81f5d41874\\tmp75d6r3gn##1-0-100.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\stable-diffusion\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\stable-diffusion\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "E:\stable-diffusion\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\stable-diffusion\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\stable-diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\stable-diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Stable-diffusion\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "E:\Stable-diffusion/extensions/SadTalker\src\gradio_demo.py", line 122, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess)
  File "E:\Stable-diffusion/extensions/SadTalker\src\facerender\animate.py", line 192, in generate
    save_video_with_watermark(path, new_audio_path, av_path, watermark= False)
  File "E:\Stable-diffusion/extensions/SadTalker\src\utils\videoio.py", line 26, in save_video_with_watermark
    shutil.move(temp_file, save_path)
  File "E:\Stable-diffusion\python\lib\shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "E:\Stable-diffusion\python\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "E:\Stable-diffusion\python\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'd3e190da-e0b7-4488-aef7-d9e1be1f6850.mp4'

**Comment by ubohex** [comment]
if it matters, I use Stable Diffusion Portable (https://github.com/serpotapov/stable-diffusion-portable)

**Comment by rusl133** [comment]
I have the same problem:
FileNotFoundError: [Errno 2] No such file or directory: '1b097bca-f231-46c4-bda6-489c7bc903a7.mp4'

**Comment by vinthony** [comment]
do you have any images in `outputs/txt2img-images/2023-xx-xx/xx.png`?

The early version of the stable-diffusion-webui will only generate the image in  `outputs/txt2img-images/xx.png` other than `outputs/txt2img-images/2023-xx-xx/xx.png`?


> refreshed, updated, rebooted, but that's not the main problem! I can load a picture from my saved ones. **The main problem is this:** Traceback (most recent call last): File "E:\Stable-diffusion\python\lib\shutil.py", line 815, in move os.rename(src, real_dst) FileNotFoundError: [WinError 2] Не удается найти указанный файл: 'd3e190da-e0b7-4488-aef7-d9e1be1f6850.mp4' -> 'E:\Stable-diffusion\outputs\SadTalker\db886a54-6317-4e8c-baaf-ab81f5d41874\tmp75d6r3gn##1-0-100.mp4'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "E:\stable-diffusion\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict output = await app.get_blocks().process_api( File "E:\stable-diffusion\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api result = await self.call_function( File "E:\stable-diffusion\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function prediction = await anyio.to_thread.run_sync( File "E:\stable-diffusion\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync return await get_asynclib().run_sync_in_worker_thread( File "E:\stable-diffusion\venv\lib\site-packages\anyio_backends_asyncio.py", line 937, in run_sync_in_worker_thread return await future File "E:\stable-diffusion\venv\lib\site-packages\anyio_backends_asyncio.py", line 867, in run result = context.run(func, *args) File "E:\Stable-diffusion\modules\call_queue.py", line 15, in f res = func(*args, **kwargs) File "E:\Stable-diffusion/extensions/SadTalker\src\gradio_demo.py", line 122, in test return_path = self.animate_from_coeff.generate(data, save_dir, pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess) File "E:\Stable-diffusion/extensions/SadTalker\src\facerender\animate.py", line 192, in generate save_video_with_watermark(path, new_audio_path, av_path, watermark= False) File "E:\Stable-diffusion/extensions/SadTalker\src\utils\videoio.py", line 26, in save_video_with_watermark shutil.move(temp_file, save_path) File "E:\Stable-diffusion\python\lib\shutil.py", line 835, in move copy_function(src, real_dst) File "E:\Stable-diffusion\python\lib\shutil.py", line 434, in copy2 copyfile(src, dst, follow_symlinks=follow_symlinks) File "E:\Stable-diffusion\python\lib\shutil.py", line 254, in copyfile with open(src, 'rb') as fsrc: FileNotFoundError: [Errno 2] No such file or directory: 'd3e190da-e0b7-4488-aef7-d9e1be1f6850.mp4'

**Comment by vinthony** [comment]
> I have the same problem: FileNotFoundError: [Errno 2] No such file or directory: '1b097bca-f231-46c4-bda6-489c7bc903a7.mp4'

this is not the real reason, try to paste the full traceback.

**Comment by ubohex** [comment]
> 
after the error, the following files are created: 
![screen](https://user-images.githubusercontent.com/52637962/232288963-1b97cb4a-09ec-41f6-ab3e-90f49ddf79af.PNG)

**Comment by vinthony** [comment]
please give me full trackback so that i can help you well.

for the first, please check the installation of `ffmpeg` are in the %PATH%.

second, please check this folder is existed : `stable-diffusion/outputs/txt2img-images/2023-xx-xx/`

**Comment by ubohex** [comment]
Resolved, but not completely:
100%|██████████████████████████████████████████████████████████████████████████████████| 22/22 [00:05<00:00,  4.11it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 22/22 [00:05<00:00,  3.99it/s]
E:\Stable-diffusion\extensions\SadTalker\checkpoints\auido2pose_00140-model.pth████████| 22/22 [00:05<00:00,  4.27it/s]
E:\Stable-diffusion\extensions\SadTalker\checkpoints\shape_predictor_68_face_landmarks.dat
E:\Stable-diffusion\extensions\SadTalker\checkpoints\facevid2vid_00189-model.pth.tar
E:\stable-diffusion\tmp\tmpbcel7f53.png
landmark Det:: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.47it/s]
3DMM Extraction In Video:: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.31it/s]
mel:: 100%|███████████████████████████████████████████████████████████████████████| 102/102 [00:00<00:00, 51034.12it/s]
audio2exp:: 100%|█████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 117.93it/s]
Face Renderer:: 100%|██████████████████████████████████████████████████████████████████| 51/51 [00:18<00:00,  2.74it/s]
height not divisible by 2 (256x273)
Traceback (most recent call last):
  File "E:\Stable-diffusion/extensions/SadTalker\src\facerender\animate.py", line 174, in generate
    torchvision.io.write_video(path,  result, fps=float(25))
  File "E:\stable-diffusion\venv\lib\site-packages\torchvision\io\video.py", line 134, in write_video
    for packet in stream.encode(frame):
  File "av\stream.pyx", line 153, in av.stream.Stream.encode
  File "av\codec\context.pyx", line 482, in av.codec.context.CodecContext.encode
  File "av\codec\context.pyx", line 291, in av.codec.context.CodecContext.open
  File "av\error.pyx", line 336, in av.error.err_check
av.error.ExternalError: [Errno 542398533] Generic error in an external library; last error log: [libx264] height not divisible by 2 (256x273)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\stable-diffusion\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\stable-diffusion\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "E:\stable-diffusion\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\stable-diffusion\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\stable-diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\stable-diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Stable-diffusion\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "E:\Stable-diffusion/extensions/SadTalker\src\gradio_demo.py", line 122, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess)
  File "E:\Stable-diffusion/extensions/SadTalker\src\facerender\animate.py", line 176, in generate
    imageio.mimsave(path, result,  fps=float(25))
NameError: name 'imageio' is not defined

**Comment by vinthony** [comment]
it seems the image is not in the squared resolution, i have fixed it in the latest version by adding a 


`import imageio`

https://github.com/Winfredy/SadTalker/blob/a2f19ce1069297c8252d3ff753d4e219b6a42706/src/facerender/animate.py#L15

**Comment by ubohex** [comment]
> it seems the image is not in the squared resolution, i have fixed it in the latest version by adding a
> 
> `import imageio`
> 
> https://github.com/Winfredy/SadTalker/blob/a2f19ce1069297c8252d3ff753d4e219b6a42706/src/facerender/animate.py#L15

It works! Thank you very much! Good luck with the development!

**Comment by rusl133** [comment]
> > it seems the image is not in the squared resolution, i have fixed it in the latest version by adding a
> > `import imageio`
> > https://github.com/Winfredy/SadTalker/blob/a2f19ce1069297c8252d3ff753d4e219b6a42706/src/facerender/animate.py#L15
> 
> It works! Thank you very much! Good luck with the development!

Дружище, как ты избавился от этой ошибки?

**Comment by ubohex** [comment]
> > > it seems the image is not in the squared resolution, i have fixed it in the latest version by adding a
> > > `import imageio`
> > > https://github.com/Winfredy/SadTalker/blob/a2f19ce1069297c8252d3ff753d4e219b6a42706/src/facerender/animate.py#L15
> > 
> > 
> > It works! Thank you very much! Good luck with the development!
> 
> Дружище, как ты избавился от этой ошибки?

Засунул все файлы ffmpeg в папку E:\Stable-diffusion\git\cmd

**Comment by SacredStories** [comment]
> it seems the image is not in the squared resolution, i have fixed it in the latest version by adding a
> 
> `import imageio`
> 
> https://github.com/Winfredy/SadTalker/blob/a2f19ce1069297c8252d3ff753d4e219b6a42706/src/facerender/animate.py#L15

Im having the same problem @ubohex seemed to be having, albeit I thought I was using the latest version of Sad Talker. Is there something I need to do to manually get your fix working?
