### ISSUE TITLE
ERROR: No matching distribution found for torch==1.12.1+cu113

### ISSUE THREAD

**Issue by SauChi666** [Winfredy/SadTalker#180]
pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113
ERROR: Could not find a version that satisfies the requirement torch==1.12.1+cu113 (from versions: 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0)
ERROR: No matching distribution found for torch==1.12.1+cu113
(sadtalker) appleid@MacM2Pro SadTalker %

**Comment by vinthony** [comment]
Please following this link for mac installation
https://github.com/Winfredy/SadTalker/blob/main/docs/install.md#mac-tested-on-m1-mac-os-133

**Comment by vinthony** [comment]
Fixed & close.

**Comment by Inquestop** [comment]
same issue in windows

**Comment by madmistermump** [comment]
This is a significant problem for new installs. Python version 3.10.6 is no longer available from python, so if you don't have it you are pretty much out of luck unless someone has an old version to install. The main issue is pytorch is not compatible with anything after 3.10.6. Python is (at the time of my post) 3.13 so unless pytorch updates their software this git is unless for new installs.

**Comment by HasseM** [comment]
Yes, serious problem on Windows. Unable to fix it as well. Need to run it standalone for control through CLI. If anyone has a solution, please tell!

Edit:
Thanks to @madmistermump I understood that I needed Python 3.10.6. So I was ALMOST able to fix it. This is what I did:
- remove existing venv folder in sadtalker
- get Python 3.10.6 from here: https://www.python.org/downloads/release/python-3106/
- install it but choose custom installation
- set installation path to c:/python310/
- in Sadtalker, change webui.bat line 4 into:  c:\python310\python -m venv venv

Now the virtual environment is made with Python 3.10.6.

But I get stuck now at:
Launching SadTalker Web UI
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
