### ISSUE TITLE
使用stable diffusion生成视频最后一步报错

### ISSUE THREAD

**Issue by coolshinejonson** [Winfredy/SadTalker#181]
环境：在stable diffusion-webui环境中
选项：proprocess 选择full，Remove head motion (works better with preprocess `full`)选中
执行到最后的时候
报错：
[aac @ 0000012f0f190bc0] Qavg: 60855.461
The generated video is named D:\AUTOMATIC1111\stable-diffusion-webui\outputs\SadTalker\b84cd82a-fb1b-47b1-9afc-2c525dde08cf/tmp7bhu2jml##功夫肩颈8yd2rztn_full.mp4
The generated video is named tmp7bhu2jml##功夫肩颈8yd2rztn in D:\AUTOMATIC1111\stable-diffusion-webui\outputs\SadTalker\b84cd82a-fb1b-47b1-9afc-2c525dde08cf
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 162, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

最后生成了一个不眨眼的视频。这个如何解决？谢谢

**Comment by vinthony** [comment]
这个异常应该不影响生成。full选项现在还不支持眨眼哈

**Comment by coolshinejonson** [comment]
明白了，谢谢。
