### ISSUE TITLE
Whether Chinese is supported ？

### ISSUE THREAD

**Issue by zcdliuwei** [Winfredy/SadTalker#2]

**Comment by zcdliuwei** [comment]
thanks again for your outstanding work !

**Comment by pikeyang** [comment]
> Although our method is trained in English, it may also perform effectively in Chinese. Please refer to the demo wavs for further demonstration.
> 
>  art_11.chinese_poem.mp4 
>  art_12.chinese_poem2.mp4

can you explain why
