### ISSUE TITLE
Generating 3D face from Audio is a good idea, can you tell me when it can be used?

### ISSUE THREAD

**Issue by 935077727** [Winfredy/SadTalker#20]
If possible. I can join the development

**Comment by vinthony** [comment]
Hi, thanks for your willingness in advance.

The 3D face can be used to generate the 3dMM rendered face model, in which we can get the 3d facial landmarks or related features, depth, or other similar features.

After getting the 3d facial landmark, we can control the digital avatar of an anime face image like [makeittalk](https://github.com/yzhou359/MakeItTalk#cartoon-faces) or a single image [youtuber](https://github.com/pkhungurn/talking-head-anime-2-demo) as here.

**Comment by 935077727** [comment]
aye, thank u

**Comment by vinthony** [comment]
launch this new feature :)
