### ISSUE TITLE
通过SD插件形式安装的，生成视频的分辨率是跟输入图片一样吗？

### ISSUE THREAD

**Issue by supernba123** [Winfredy/SadTalker#208]
我用了sd插件的方式安装，生成的视频分辨率跟输入图片不一样，输入图片用的是 512*768，生成的视频给改回 512*512 了，而且分辨率明显非常低，勾选了 full mode，也勾选了 enhance，请问是要另行设置吗？

**Comment by supernba123** [comment]
是别的问题导致的

**Comment by muximuxi** [comment]
请问分辨率变低为问题是怎么解决的呀？
