### ISSUE TITLE
RuntimeError: Unable to open checkpoints/shape_predictor_68_face_landmarks.dat

### ISSUE THREAD

**Issue by huangxin168** [Winfredy/SadTalker#21]
Thanks for your great work!
Flollow the process, have put all checkpoint files in the checkpoints path, but got this error:

python3 inference.py --driven_audio assets/nhk.wav --source_image assets/guren3.png --result_dir assets
checkpoints/epoch_20.pth

Traceback (most recent call last):
  File "inference.py", line 98, in <module>
    main(args)
  File "inference.py", line 48, in main
    preprocess_model = CropAndExtract(path_of_lm_croper, path_of_net_recon_model, dir_of_BFM_fitting, device)
  File "/SadTalker/preprocess.py", line 45, in __init__
    self.croper = Croper(path_of_lm_croper)
  File "/SadTalker/croper.py", line 38, in __init__
    self.predictor = dlib.shape_predictor(path_of_lm)
RuntimeError: Unable to open checkpoints/shape_predictor_68_face_landmarks.dat

**Comment by onnoink** [comment]
run utils/download_models.sh, it will download all the models that needed by this repo.

**Comment by vinthony** [comment]
make sure you have download all the checkpoints and save it in `./checkpoints/`

**Comment by huangxin168** [comment]
sh scripts/download_models.sh 
will download all the models
