### ISSUE TITLE
我的mac m1 max风扇从来不转。一执行生成CPU飙到顶了，话说能用到GPU吗？

### ISSUE THREAD

**Issue by StruggleYang** [Winfredy/SadTalker#230]
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/20719880/233915963-7437396b-82cb-4eb8-beed-5f947eb4c3c5.png">
电脑发热太厉害怕搞挂了，不得不停止了😄

**Comment by vinthony** [comment]
MAC推荐直接用online 服务，huggingface或者colab都很方便~

**Comment by vinthony** [comment]
conv3d不支持mps，只能等torch更新了。

**Comment by StruggleYang** [comment]
> 

我乖乖去用在线的了
