### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '13daec78-8db3-4562-86b7-b1a5029846ea.mp4'

### ISSUE THREAD

**Issue by cyco-creates** [Winfredy/SadTalker#232]
Extention DOES create a video and an audio, but it fails to merge them.
I get an error the system can't find an output video.

See [attached screenshot](https://imgur.com/a/khnwFpp) of an output map

**Comment by vinthony** [comment]
please ensure you have the FFMPEG enabled.

**Comment by cyco-creates** [comment]
I have downloaded and installed it. Should I enable it manually somewhere?

**Comment by cyco-creates** [comment]
Yeah thanks, it works now.

**Comment by vinthony** [comment]
cool, i will close this issue since it has been solved.

**Comment by cstuart1310** [comment]
Solution for anyone who has FFMPEG installed / is on linux: Make sure your inputted video has an audio channel, even if it is silent. Eg in Adobe Premiere I have a sequence's audio channel across the entire input clip, with no sound in it. For some reason this works lol
