### ISSUE TITLE
RuntimeError: Found no NVIDIA driver on your system

### ISSUE THREAD

**Issue by dn-bit** [Winfredy/SadTalker#24]
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

Sir can you please explain how we eliminate this issue ?

**Comment by vinthony** [comment]
hi, please make sure you have cuda enable. or you can try our online demo from colab https://colab.research.google.com/github/Winfredy/SadTalker/blob/main/quick_demo.ipynb
