### ISSUE TITLE
是否有支持全身图打算

### ISSUE THREAD

**Issue by dragonyjd** [Winfredy/SadTalker#26]
各位大佬好，现在是从提供的全身图中CROP出256*256的人脸，通过增强模型后输出 512*512的。请问下，后期 是否有计划将CROP的人脸，放回全身图中CROP的位置 ？就是像D-ID那样的原图，不是只扣人脸

此外，我发现CROP后的图基本上是整体在动，比如肩膀的衣服，如果放回原来的全身图中，在生成的视频中也会有肩膀的衣服变动不衔接

**Comment by magicleo** [comment]
+1 同问是否有支持全身图打算

**Comment by vinthony** [comment]
Hi, 支持全身图将是一个很不错的功能，我们可以试试看，同时如果社区能够有大佬帮我们一起做我们也非常欢迎。

**Comment by 2793145003** [comment]
可以用分割提取出脸和头发的区域，然后合并图片。
不过脸会一直移动有点怪。

**Comment by dragonyjd** [comment]
> Hi, 支持全身图将是一个很不错的功能，我们可以试试看，同时如果社区能够有大佬帮我们一起做我们也非常欢迎。

支持大佬 ，辛苦

**Comment by dragonyjd** [comment]
> 可以用分割提取出脸和头发的区域，然后合并图片。 不过脸会一直移动有点怪。

可以把CROP放回去，有返回CROP位置的，但是CROP区域整体会动，很不自然的

**Comment by 2793145003** [comment]
> > 可以用分割提取出脸和头发的区域，然后合并图片。 不过脸会一直移动有点怪。
> 
> 可以把CROP放回去，有返回CROP位置的，但是CROP区域整体会动，很不自然的

就是在crop的基础上做的。原图crop位置的分割和生成视频的分割求或作为mask，合并后贴回crop位置。

**Comment by vinthony** [comment]
> > > 可以用分割提取出脸和头发的区域，然后合并图片。 不过脸会一直移动有点怪。
> > 
> > 
> > 可以把CROP放回去，有返回CROP位置的，但是CROP区域整体会动，很不自然的
> 
> 就是在crop的基础上做的。原图crop位置的分割和生成视频的分割求或作为mask，合并后贴回crop位置。

这里贴回去的时候可以考虑固定头动参数，再加上一些工程优化没准会好一些。

**Comment by 2793145003** [comment]
> > > > 可以用分割提取出脸和头发的区域，然后合并图片。 不过脸会一直移动有点怪。
> > > 
> > > 
> > > 可以把CROP放回去，有返回CROP位置的，但是CROP区域整体会动，很不自然的
> > 
> > 
> > 就是在crop的基础上做的。原图crop位置的分割和生成视频的分割求或作为mask，合并后贴回crop位置。
> 
> 这里贴回去的时候可以考虑固定头动参数，再加上一些工程优化没准会好一些。

头动参数调为0很有用。但还是会晃动。
我试过光流法（结果会扭曲）和图片特征点（结果会闪烁）希望有大佬能解决晃动的问题，至少头部动作能平滑一点就好了……

**Comment by vinthony** [comment]
> > > > > 可以用分割提取出脸和头发的区域，然后合并图片。 不过脸会一直移动有点怪。
> > > > 
> > > > 
> > > > 可以把CROP放回去，有返回CROP位置的，但是CROP区域整体会动，很不自然的
> > > 
> > > 
> > > 就是在crop的基础上做的。原图crop位置的分割和生成视频的分割求或作为mask，合并后贴回crop位置。
> > 
> > 
> > 这里贴回去的时候可以考虑固定头动参数，再加上一些工程优化没准会好一些。
> 
> 头动参数调为0很有用。但还是会晃动。 我试过光流法（结果会扭曲）和图片特征点（结果会闪烁）希望有大佬能解决晃动的问题，至少头部动作能平滑一点就好了……

有没有一些face parser之后贴回去的例子，我看看哈？

**Comment by 2793145003** [comment]
> 有没有一些face parser之后贴回去的例子，我看看哈？

有的，我恰个饭先……

**Comment by 2793145003** [comment]
> 有没有一些face parser之后贴回去的例子，我看看哈？

为了速度只分割了原图，没有分割视频。
https://user-images.githubusercontent.com/24595900/226799784-c7ed61f4-e645-4f65-83bd-c6297d1e2233.mp4

**Comment by vinthony** [comment]
没准可以试试把crop区域变大一些，然后再利用分割把原图头部抠出来，再做inpainting？

或者如果只是二次元图像可以考虑等我们3d face landmarks部分写好之后直接连接 [easy-vtuber](https://github.com/yuyuyzl/EasyVtuber)

**Comment by 2793145003** [comment]
> 没准可以试试把crop区域变大一些，然后再利用分割把原图头部抠出来，再做inpainting？
> 
> 或者如果只是二次元图像可以考虑等我们3d face landmarks部分写好之后直接连接 [easy-vtuber](https://github.com/yuyuyzl/EasyVtuber)

狠狠期待了。
抠出整个头是目前最没有违和感的做法，就是脖子不动脑袋在晃会很怪x
这个晃动的原因是什么呢？是poseVAE在晃吗？有没有办法可以减轻晃动？

**Comment by vinthony** [comment]
> > 没准可以试试把crop区域变大一些，然后再利用分割把原图头部抠出来，再做inpainting？
> > 或者如果只是二次元图像可以考虑等我们3d face landmarks部分写好之后直接连接 [easy-vtuber](https://github.com/yuyuyzl/EasyVtuber)
> 
> 狠狠期待了。 抠出整个头是目前最没有违和感的做法，就是脖子不动脑袋在晃会很怪x 这个晃动的原因是什么呢？将pose和exp分别设为0之后都在晃，而且face3d也很稳，所以应该是OcclusionAwareSPADEGenerator的问题？？？

是3dmm到unsupervised 3d keypoints空间的映射问题。目前2d视频的方案很难拿到一对一的解。

**Comment by 2793145003** [comment]
> 是3dmm到unsupervised 3d keypoints空间的映射问题。目前2d视频的方案很难拿到一对一的解。

3dmm不应该修改人的位置，没有办法通过loss之类的限定一下吗？（不懂瞎说）

**Comment by vinthony** [comment]
> 感觉用face3d转face-vid2vid的稳定性更高一些 原本的结果：https://user-images.githubusercontent.com/24595900/227165364-d9a58a25-a9cd-45f4-b211-5fb067e25e2e.mp4 face-vid2vid：https://user-images.githubusercontent.com/24595900/227165432-26e757dc-b8ef-49cb-8d6a-03db837f6e97.mp4

非常有趣的尝试，有视觉信息的引导可能确实稳定一些

**Comment by vinthony** [comment]
> > 是3dmm到unsupervised 3d keypoints空间的映射问题。目前2d视频的方案很难拿到一对一的解。
> 
> 3dmm不应该修改人的位置，没有办法通过loss之类的限定一下吗？（不懂瞎说）

这部分可能可以有一些解耦的更好的办法，会在后面的模型迭代或者可以留作future work :)

**Comment by 2793145003** [comment]
[speech2gesture](https://github.com/amirbar/speech2gesture)可以从音频生成手势
[Thin-Plate Spline Motion Model for Image Animation](https://github.com/yoyo-nb/Thin-Plate-Spline-Motion-Model)可以根据参考视频生成人物动作
如果像生成3dmm一样使用音频生成关键点和动作预测的话，人物就可以动起来了……（做梦）

**Comment by vinthony** [comment]
> [speech2gesture](https://github.com/amirbar/speech2gesture)可以从音频生成手势 [Thin-Plate Spline Motion Model for Image Animation](https://github.com/yoyo-nb/Thin-Plate-Spline-Motion-Model)可以根据参考视频生成人物动作 如果像生成3dmm一样使用音频生成关键点和动作预测的话，人物就可以动起来了……（做梦）

多谢以上宝贵的建议~

全身的 single image animation 还是比较难哈，speech2gesture目前的算法应该还属于不怎么可用的阶段~

TPS 用来做人脸应该还行，人体可能会涉及到手部的问题很难处理。

3d生成关键点或者类似的模型然后渲染到2d可能是一个更容易一些流程~

**Comment by vinthony** [comment]
A relatively basic solution is proposed as discussed in #35 by a `resize mode` in our updated code for a larger crop of the original image, which can handle a face and shoulder image animation by our algorithm. Have fun if it is helpful.

**Comment by dragonyjd** [comment]
![image](https://user-images.githubusercontent.com/23169538/228448896-261e9829-19c3-4bbe-a51c-4d708d020056.png)
@vinthony 感谢支持，提 一个BUG，整 个视频都抽抽了

**Comment by dragonyjd** [comment]
![gdg](https://user-images.githubusercontent.com/23169538/228449871-18d792bf-63cc-4104-986b-283cb1bb8dc7.jpg)
这张是原图

**Comment by vinthony** [comment]
> ![image](https://user-images.githubusercontent.com/23169538/228448896-261e9829-19c3-4bbe-a51c-4d708d020056.png) @vinthony 感谢支持，提 一个BUG，整 个视频都抽抽了

目前只是一个替代方案哈，可以在人脸的基础上稍微大一些，但是不是全身。

**Comment by dragonyjd** [comment]
> 

好的，看样竖屏，小半身效果能好些

**Comment by dragonyjd** [comment]
> > ![image](https://user-images.githubusercontent.com/23169538/228448896-261e9829-19c3-4bbe-a51c-4d708d020056.png) @vinthony 感谢支持，提 一个BUG，整 个视频都抽抽了
> 
> 目前只是一个替代方案哈，可以在人脸的基础上稍微大一些，但是不是全身。

好的，看样竖屏，小半身效果能好些

**Comment by 2793145003** [comment]
我用[L1](https://github.com/ishank-juneja/L1-optimal-paths-Stabilization)对结果做了视频稳定，再加上still_mode，就可以把脑袋按回原图上了。
代价是，脸变得有点糊……
目测结果再做超分应该就差不多了，但加了一堆trick就很麻烦也很慢。

**Comment by vinthony** [comment]
> 

cool, 这里面肯定可以通过训练模型解决其中的大部分问题~

**Comment by MrDerrekTeng** [comment]
这个是跟训练数据集有关么？有可能会在近期支持么？

另外，我在colab上跑，当音频超过一定长度，生成的video就没有得到保存。这是跟机器配置有关么？

**Comment by magicleo** [comment]
@2793145003 能贴一下代码学习下吗？

**Comment by 2793145003** [comment]
> @2793145003 能贴一下代码学习下吗？

没啥值得贴的代码，就在quick_demo后面加上
```
# 平滑
!cd L1-optimal-paths-Stabilization/; python L1optimal.py -i "/content/result.mp4" -o "/content/l1.mp4" -crop-ratio 1.0
# 超分
import mmcv
video = mmcv.VideoReader('/content/l1.mp4')
video.cvt2frames('/content/CodeFormer/inputs/test')
CODEFORMER_FIDELITY = 1.0
!cd CodeFormer; python inference_codeformer.py -w $CODEFORMER_FIDELITY --input_path inputs/test --bg_upsampler realesrgan
mmcv.frames2video('/content/CodeFormer/results/test_1.0/final_results/', 'codeformer.mp4', filename_tmpl='{:06d}.png')
```
L1和CodeFormer在github里搜就行，可能需要改一下路径，超分不看中间结果的话用ffmpeg比较快，然后把结果的脑袋和头发部分扣出来用seamlessClone贴回去就行了。
三十秒的音频，这一套下来要十几分钟（不超分的话会快很多但很糊），所以还是别用这套直接考虑搞模型和数据优化3dmm的生成结果比较好……

**Comment by vinthony** [comment]
上线了一个beta版本的全身解决方案~ 小图正脸还行


https://user-images.githubusercontent.com/4397546/229483628-2ee6ca09-6fc5-4746-a7d1-8c004ab976f5.mp4

**Comment by MrDerrekTeng** [comment]
感觉用--still --enhancer 虽然分辨率低，但是效果比--full_img_enhancer 好，后者处理之后脸看上有点卡通脸。 如果要是模型可是用high resolution图片训练，感觉就不太需要gfpgan了

**Comment by vinthony** [comment]
> 感觉用--still --enhancer 虽然分辨率低，但是效果比--full_img_enhancer 好，后者处理之后脸看上有点卡通脸。 如果要是模型可是用high resolution图片训练，感觉就不太需要gfpgan了

是的，正在考虑训练一个512x512的高清faceRender, 之前的训练数据比较少。

**Comment by flyingdoor** [comment]
我把图片以crop区域为中心拆成5块（头，头左，头右，上，下），再用cv2的全景Stitcher来做拼接，得到单帧图的贴合效果很不错，清晰度也可以。遗憾的是合成的视频抖动严重，人像忽前忽后。通过拼接后的图的四角坐标和原图四角坐标做一次透视转换可以缓解抖动但是无法彻底消除。

**Comment by MrDerrekTeng** [comment]
用--still --enhancer 这里有个bug，如果source_image 是 video，则会在src/utils/paste_pic.py    full_img = cv2.imread(pic_path) 之后报错。然后full size video就不会保存。

**Comment by AI796** [comment]
使用LIA可以平替目前的GAN渲染器，LIA项目网址：https://github.com/wyhsirius/LIA
我写的Demo:
https://github.com/AI796/SadTalker/blob/SadTalker_with_stylegan_renderer/src/stylegan_renderer/stylegan_renderer.py
权重可以在上面LIA项目网站下载，Demo使用rasterizer.py渲染结果（作为驱动图）和参考头像（或全身）作为输入。
该方法借由stylegan2-pytorch预训练神经网路的生成能力，牙齿和身体由该网络自动生成，所以清晰度和稳定性更高，无抖动和模糊。

**Comment by vinthony** [comment]
> 使用LIA可以平替目前的GAN渲染器，LIA项目网址：https://github.com/wyhsirius/LIA 我写的Demo: https://github.com/AI796/SadTalker/blob/SadTalker_with_stylegan_renderer/src/stylegan_renderer/stylegan_renderer.py 权重可以在上面LIA项目网站下载，Demo使用rasterizer.py渲染结果（作为驱动图）和参考头像（或全身）作为输入。 该方法借由stylegan2-pytorch预训练神经网路的生成能力，牙齿和身体由该网络自动生成，所以清晰度和稳定性更高，无抖动和模糊。

Cool，如果从3d走的话可能抖动会少很多，我们也会跟进3D的方案。

**Comment by AI796** [comment]
也许从landmark直接算出gan需要的eigen value是捷径，省去了torch3d的计算开销, psp应该有机会实现这一转换

**Comment by vinthony** [comment]
> 使用LIA可以平替目前的GAN渲染器，LIA项目网址：https://github.com/wyhsirius/LIA 我写的Demo: https://github.com/AI796/SadTalker/blob/SadTalker_with_stylegan_renderer/src/stylegan_renderer/stylegan_renderer.py 权重可以在上面LIA项目网站下载，Demo使用rasterizer.py渲染结果（作为驱动图）和参考头像（或全身）作为输入。 该方法借由stylegan2-pytorch预训练神经网路的生成能力，牙齿和身体由该网络自动生成，所以清晰度和稳定性更高，无抖动和模糊。

如果可以，也可以pull requests, 我也会把从3d走+视觉驱动的方案集成进来。

**Comment by vinthony** [comment]
> 也许从landmark直接算出gan需要的eigen value是捷径，省去了torch3d的计算开销, psp应该有机会实现这一转换 这有个项目：https://github.com/endo-yuki-t/Fewshot-SMIS

根据我的猜测，psp可能对于驱动任务不太稳定。

**Comment by AI796** [comment]
想法不是太完整，先email交流吧

**Comment by vinthony** [comment]
> 

嗯嗯

**Comment by MrDerrekTeng** [comment]
> 使用LIA可以平替目前的GAN渲染器，LIA项目网址：https://github.com/wyhsirius/LIA 我写的Demo: https://github.com/AI796/SadTalker/blob/SadTalker_with_stylegan_renderer/src/stylegan_renderer/stylegan_renderer.py 权重可以在上面LIA项目网站下载，Demo使用rasterizer.py渲染结果（作为驱动图）和参考头像（或全身）作为输入。 该方法借由stylegan2-pytorch预训练神经网路的生成能力，牙齿和身体由该网络自动生成，所以清晰度和稳定性更高，无抖动和模糊。

你是把这些设置好值之后，直接python stylegan_renderer.py么？
    img_path="" # source img 256*256
    driving_video_path="" # driving video generated by rasterizer
    tmp_video_path="" #folder name to save temp files
    final_out_video_path="" # final result
    audio_path="" # source audio
我run了一下有错误
100%|███████████████████████████████████████| 1169/1169 [00:30<00:00, 38.53it/s]
Traceback (most recent call last):
  File "src/stylegan_renderer/stylegan_renderer.py", line 728, in <module>
    save_video(
  File "src/stylegan_renderer/stylegan_renderer.py", line 35, in save_video
    vid = vid_target_recon.permute(0, 2, 3, 4, 1)
RuntimeError: number of dims don't match in permute
你遇到过这个问题么？
另外，我看注释说的是img要是256*256，你是怎么支持全身图的呢？

**Comment by AI796** [comment]
> > 使用LIA可以平替目前的GAN渲染器，LIA项目网址：https://github.com/wyhsirius/LIA 我写的Demo: https://github.com/AI796/SadTalker/blob/SadTalker_with_stylegan_renderer/src/stylegan_renderer/stylegan_renderer.py 权重可以在上面LIA项目网站下载，Demo使用rasterizer.py渲染结果（作为驱动图）和参考头像（或全身）作为输入。 该方法借由stylegan2-pytorch预训练神经网路的生成能力，牙齿和身体由该网络自动生成，所以清晰度和稳定性更高，无抖动和模糊。
> 
> 你是把这些设置好值之后，直接python stylegan_renderer.py么？ img_path="" # source img 256_256 driving_video_path="" # driving video generated by rasterizer tmp_video_path="" #folder name to save temp files final_out_video_path="" # final result audio_path="" # source audio 我run了一下有错误 100%|███████████████████████████████████████| 1169/1169 [00:30<00:00, 38.53it/s] Traceback (most recent call last): File "src/stylegan_renderer/stylegan_renderer.py", line 728, in save_video( File "src/stylegan_renderer/stylegan_renderer.py", line 35, in save_video vid = vid_target_recon.permute(0, 2, 3, 4, 1) RuntimeError: number of dims don't match in permute 你遇到过这个问题么？ 另外，我看注释说的是img要是256_256，你是怎么支持全身图的呢？

感谢关注，这是一个分支，只是演示了一下如何使用LIA渲染最后一步，如果需要跟主项目形成pipeline，还需要填入对应主项目的文件存储位置，以及做一下输出的格式转化，如果需要的话我今天完善一下，抱歉。

**Comment by MrDerrekTeng** [comment]
> > > 使用LIA可以平替目前的GAN渲染器，LIA项目网址：https://github.com/wyhsirius/LIA 我写的Demo: https://github.com/AI796/SadTalker/blob/SadTalker_with_stylegan_renderer/src/stylegan_renderer/stylegan_renderer.py 权重可以在上面LIA项目网站下载，Demo使用rasterizer.py渲染结果（作为驱动图）和参考头像（或全身）作为输入。 该方法借由stylegan2-pytorch预训练神经网路的生成能力，牙齿和身体由该网络自动生成，所以清晰度和稳定性更高，无抖动和模糊。
> > 
> > 
> > 你是把这些设置好值之后，直接python stylegan_renderer.py么？ img_path="" # source img 256_256 driving_video_path="" # driving video generated by rasterizer tmp_video_path="" #folder name to save temp files final_out_video_path="" # final result audio_path="" # source audio 我run了一下有错误 100%|███████████████████████████████████████| 1169/1169 [00:30<00:00, 38.53it/s] Traceback (most recent call last): File "src/stylegan_renderer/stylegan_renderer.py", line 728, in save_video( File "src/stylegan_renderer/stylegan_renderer.py", line 35, in save_video vid = vid_target_recon.permute(0, 2, 3, 4, 1) RuntimeError: number of dims don't match in permute 你遇到过这个问题么？ 另外，我看注释说的是img要是256_256，你是怎么支持全身图的呢？
> 
> 感谢关注，这是一个分支，只是演示了一下如何使用LIA渲染最后一步，如果需要跟主项目形成pipeline，还需要填入对应主项目的文件存储位置，以及做一下输出的格式转化，如果需要的话我今天完善一下，抱歉。

YES! PLEASE! THANKS!

**Comment by AI796** [comment]
> > > > 使用LIA可以平替目前的GAN渲染器，LIA项目网址：https://github.com/wyhsirius/LIA 我写的Demo: https://github.com/AI796/SadTalker/blob/SadTalker_with_stylegan_renderer/src/stylegan_renderer/stylegan_renderer.py 权重可以在上面LIA项目网站下载，Demo使用rasterizer.py渲染结果（作为驱动图）和参考头像（或全身）作为输入。 该方法借由stylegan2-pytorch预训练神经网路的生成能力，牙齿和身体由该网络自动生成，所以清晰度和稳定性更高，无抖动和模糊。
> > > 
> > > 
> > > 你是把这些设置好值之后，直接python stylegan_renderer.py么？ img_path="" # source img 256_256 driving_video_path="" # driving video generated by rasterizer tmp_video_path="" #folder name to save temp files final_out_video_path="" # final result audio_path="" # source audio 我run了一下有错误 100%|███████████████████████████████████████| 1169/1169 [00:30<00:00, 38.53it/s] Traceback (most recent call last): File "src/stylegan_renderer/stylegan_renderer.py", line 728, in save_video( File "src/stylegan_renderer/stylegan_renderer.py", line 35, in save_video vid = vid_target_recon.permute(0, 2, 3, 4, 1) RuntimeError: number of dims don't match in permute 你遇到过这个问题么？ 另外，我看注释说的是img要是256_256，你是怎么支持全身图的呢？
> > 
> > 
> > 感谢关注，这是一个分支，只是演示了一下如何使用LIA渲染最后一步，如果需要跟主项目形成pipeline，还需要填入对应主项目的文件存储位置，以及做一下输出的格式转化，如果需要的话我今天完善一下，抱歉。
> 
> YES! PLEASE! THANKS!

代码已经更新，删除了save_video方法中错误的重复代码，不过我注意到main repo最近做了比较大的更新，原pytorch3d在目前版本的main repo环境下需要重新编译，难度应该不小。
这个branch不解决头像视频回帖到原图的方法，请参考相关的main repo代码。
由于main repo更新较多，目前的branch并没有尝试集成回pipeline中（需要修改多处）

**Comment by MrDerrekTeng** [comment]
> > > > > 使用LIA可以平替目前的GAN渲染器，LIA项目网址：https://github.com/wyhsirius/LIA 我写的Demo: https://github.com/AI796/SadTalker/blob/SadTalker_with_stylegan_renderer/src/stylegan_renderer/stylegan_renderer.py 权重可以在上面LIA项目网站下载，Demo使用rasterizer.py渲染结果（作为驱动图）和参考头像（或全身）作为输入。 该方法借由stylegan2-pytorch预训练神经网路的生成能力，牙齿和身体由该网络自动生成，所以清晰度和稳定性更高，无抖动和模糊。
> > > > 
> > > > 
> > > > 你是把这些设置好值之后，直接python stylegan_renderer.py么？ img_path="" # source img 256_256 driving_video_path="" # driving video generated by rasterizer tmp_video_path="" #folder name to save temp files final_out_video_path="" # final result audio_path="" # source audio 我run了一下有错误 100%|███████████████████████████████████████| 1169/1169 [00:30<00:00, 38.53it/s] Traceback (most recent call last): File "src/stylegan_renderer/stylegan_renderer.py", line 728, in save_video( File "src/stylegan_renderer/stylegan_renderer.py", line 35, in save_video vid = vid_target_recon.permute(0, 2, 3, 4, 1) RuntimeError: number of dims don't match in permute 你遇到过这个问题么？ 另外，我看注释说的是img要是256_256，你是怎么支持全身图的呢？
> > > 
> > > 
> > > 感谢关注，这是一个分支，只是演示了一下如何使用LIA渲染最后一步，如果需要跟主项目形成pipeline，还需要填入对应主项目的文件存储位置，以及做一下输出的格式转化，如果需要的话我今天完善一下，抱歉。
> > 
> > 
> > YES! PLEASE! THANKS!
> 
> 代码已经更新，删除了save_video方法中错误的重复代码，不过我注意到main repo最近做了比较大的更新，原pytorch3d在目前版本的main repo环境下需要重新编译，难度应该不小。 这个branch不解决头像视频回帖到原图的方法，请参考相关的main repo代码。 由于main repo更新较多，目前的branch并没有尝试集成回pipeline中（需要修改多处）

多谢尝试！期待整合后的版本，谢谢！

**Comment by MrDerrekTeng** [comment]
除了still参数，有没有什么方法可以让头完全不动呢？

**Comment by MrDerrekTeng** [comment]
另外，我尝试用GFPGAN RestoreFormer，其效果对于单张图片非常好，脸部细节restore的很detail，但是为什么在这里--enhancer RestoreFormer的效果反而不如gfpgan呢？

**Comment by vinthony** [comment]
在v0.0.2中我们支持了全身图的例子，把gfpgan的处理放在了最后，可以极大增强画质， 参考： https://github.com/Winfredy/SadTalker/releases/tag/v0.0.2

**Comment by hly990** [comment]
> 除了still参数，有没有什么方法可以让头完全不动呢？
> 
> 这里https://github.com/Winfredy/SadTalker/blob/main/src/generate_facerender_batch.py#L40
> 
> ```
> if still_mode:
>     generated_3dmm[:, 64:] = np.repeat(source_semantics[:, 64:], generated_3dmm.shape[0], axis=0)
> ```
> 
> 有可能引入frozen_mode，然后通过上面类似的方法让头完全不动么？这样的话，再用ref_eyeblink是不是就会达到很好的效果？
> 
> 抱歉本人对于ML相关开发一窍不通，问些小白的问题请见谅。

让头部不动，研究出来了吗？

**Comment by AIhasArrived** [comment]
Helo good folks, I dont speak english, but you all seem very experienced,
I am getting error about background anhancer :

I am using google collab 
**(File "/content/SadTalker/src/utils/face_enhancer.py", line 80, in enhancer_generator_no_len
    from realesrgan import RealESRGANer
ModuleNotFoundError: No module named 'realesrgan')**
What can I do to solve it?
