### ISSUE TITLE
GPU usage Settings

### ISSUE THREAD

**Issue by MoroseYu** [Winfredy/SadTalker#27]
Hi, great work !
Computer 16G GPU, but the maximum can only use 6G, I want it to generate results faster, where is this value set? Look forward to your reply. Thank you~

**Comment by vinthony** [comment]
<img width="885" alt="image" src="https://user-images.githubusercontent.com/4397546/226777470-d2399513-d37e-4d2c-a244-de7a282154ab.png">
just change the `--batch_size` to larger value, like 8 .

**Comment by MoroseYu** [comment]
> <img alt="图像" width="885" src="https://user-images.githubusercontent.com/4397546/226777470-d2399513-d37e-4d2c-a244-de7a282154ab.png">
> 
> 只需将 `--batch_size` 更改为更大的值，例如 8 。

Thanks for your reply~
Currently, it can only be applied to the 'Face Renderer' stage,  'Face Enhancer' is not in effect yet

**Comment by AIhasArrived** [comment]
Hello @MoroseYu  did you find how to apply the fastening correclty? If yes please tell me.
@vinthony  please add info if you have.
