### ISSUE TITLE
colab book running issue

### ISSUE THREAD

**Issue by dn-bit** [Winfredy/SadTalker#28]
there is problem with 

 no module found gfpgan
how to clone gfpgan in notebook can you please explore it

no such directory examples/results
I have created directory same as need
but now also showing same error

**Comment by vinthony** [comment]
fixed gfpgan install problem.

**Comment by dn-bit** [comment]
> GPU can be handled via the hint at this green line： ![image](https://user-images.githubusercontent.com/4397546/226908548-0f603558-1ed4-4fbb-acde-fcc477d11804.png)
> 
> You don't need to create the folder. if you run anything correctly, the result will be shown. ![image](https://user-images.githubusercontent.com/4397546/226908895-714f0e96-a659-4100-a86b-79321a3be203.png)

perfect buddy ! colab notebook working absolutely fine...

Thanks
