### ISSUE TITLE
感觉可以考虑加入codeformer

### ISSUE THREAD

**Issue by 2793145003** [Winfredy/SadTalker#29]
codeformer：https://github.com/sczhou/CodeFormer
在二次元图片上的表现比GFPGAN好很多
结果：
生成视频：https://user-images.githubusercontent.com/24595900/226800506-77d2dca8-3922-481c-809c-ccc213f70bcf.mp4
GFPGAN：https://user-images.githubusercontent.com/24595900/226800547-49867fcd-e738-4768-a1ef-40fee143e73b.mp4
codeformer：https://user-images.githubusercontent.com/24595900/226800615-7cc4133c-42d9-4d95-b5e9-4730a386716c.mp4
（视频无法在线看的话可能要右键保存链接）
当然只是建议，自己加起来也很方便x

**Comment by vinthony** [comment]
cool, 会支持。
