### ISSUE TITLE
眼睛动作的问题

### ISSUE THREAD

**Issue by linghai06** [Winfredy/SadTalker#30]
嗨， 感谢分享那么棒的工作。

我发现生成的视频眼睛一般都没法完全闭上，所以稍微有点不自然，是否有改进方法呢？thanks！

**Comment by 2793145003** [comment]
我生成2D的结果还正常。
但3D face的结果从来不眨眼睛……或者说把pose关掉之后就只动嘴皮子……

**Comment by vinthony** [comment]
可以参考我们最新的ref-video mode.
