### ISSUE TITLE
如何添加到sd

### ISSUE THREAD

**Issue by dvdcjw** [Winfredy/SadTalker#31]
如何添加到stable diffusion里?像演示视频一样

**Comment by Winfredy** [comment]
我们之后会开源这部分代码

**Comment by vinthony** [comment]
和 #11 重复

**Comment by vinthony** [comment]
Add sd-extension.  Just install it in extensions -> install from URL -> https://github.com/Winfredy/SadTalker, which may take several minutes to download the models automatically.
