### ISSUE TITLE
load facevid2vid_00189-model.pth.tar error

### ISSUE THREAD

**Issue by lmousexu00** [Winfredy/SadTalker#33]
i download from https://github.com/Winfredy/SadTalker/releases/tag/v0.0.1 or  google drive, when the program load  facevid2vid_00189-model.pth.tar, raise KeyError: "filename 'storages' not found"
Is the file I downloaded corrupted ?

**Comment by dn-bit** [comment]
wget https://github.com/Winfredy/SadTalker/releases/download/v0.0.1/facevid2vid_00189-model.pth.tar -O ./checkpoints/facevid2vid_00189-model.pth.tar

run upper on terminal else download from below link and try
https://github.com/Winfredy/SadTalker/releases/download/v0.0.1/facevid2vid_00189-model.pth.tar

-just explore inside library open scripts/download_models.sh you got all the link with model link

just run this in terminal 
bash scripts/download_models.sh      for all model download and setup 


may it's helpful to you

**Comment by lmousexu00** [comment]
The file download is corrupted, just download it again。 tks
