### ISSUE TITLE
About expression

### ISSUE THREAD

**Issue by dn-bit** [Winfredy/SadTalker#34]
as its said sadtalker so expression are in sad but if we want our output in joyful expression or any other expression rather than same sad expression so how we implement for this ?

and library also work for video's same expression just give audio so he convert in to lips sync and other thing like expression of video and other thing are same?

**Comment by 2793145003** [comment]
see styletalk: https://github.com/fuxivirtualhuman/styletalk
but I'm not sure if this is what you want...

**Comment by dn-bit** [comment]
> see styletalk: https://github.com/fuxivirtualhuman/styletalk but I'm not sure if this is what you want...

but suppose i set audio as song but movement of face is same like serious so i just  want to tell  you that how i changes so that in song face is freely move  and do his movement accordingly

**Comment by yablokoff** [comment]
> see styletalk: https://github.com/fuxivirtualhuman/styletalk but I'm not sure if this is what you want...

Is there anything like that but already available?

**Comment by vinthony** [comment]
Hacking the source image into different expressions may produce an emotional talking head video. : )


This repo might be helpful： https://tengfei-wang.github.io/HFGI/

<img width="727" alt="image" src="https://user-images.githubusercontent.com/4397546/227696471-b1548258-8d22-4e16-a495-678a73d3a874.png">
