### ISSUE TITLE
如何设置能把生成的人像再大一些呢？

### ISSUE THREAD

**Issue by zhang565055965** [Winfredy/SadTalker#35]
如何设置能把生成的人像再大一些呢？稍微露出多一些肩膀也好，有时只有头和膀子

**Comment by dn-bit** [comment]
agree if we insert full image and return with face expression and other part also some moment then its very good thing

**Comment by 2793145003** [comment]
只要把这里（https://github.com/Winfredy/SadTalker/blob/df0be73c6b24975438b98a6e4bb7ce7928505a8c/src/utils/preprocess.py#L84）改成False手动crop就行了……
但脑袋之外的部分越多结果越扭曲……

**Comment by vinthony** [comment]
增加了resize mode 的选项， 可以处理相对大的人像crop

https://user-images.githubusercontent.com/4397546/228439718-1dc5d3e2-aa15-43f6-b9ec-4976aacd62b2.mp4
