### ISSUE TITLE
code running in local without gpu is possible??

### ISSUE THREAD

**Issue by dn-bit** [Winfredy/SadTalker#36]
Hi sir,

its possible to run code in local without gpu only using cpu??

i know colab book is option but i need to run in local

**Comment by vinthony** [comment]
try `python inference.py --cpu`

**Comment by dn-bit** [comment]
> try `python inference.py --cpu`

not working same error coming...


sir have another question can you please solve it 

- suppose i set audio as song but movement of face is same like serious so i just want to tell you that how i changes so that in song face is freely move and do his movement accordingly

**Comment by risharde** [comment]
Why is this closed? This is still an issue. On the docker, same problem

**Comment by Maximus48p** [comment]
same issue
