### ISSUE TITLE
I don't know where to put "w/ still mode"

### ISSUE THREAD

**Issue by microgits** [Winfredy/SadTalker#38]
Thanks! Great product, I am running on RTX 3090.

I noticed that you have added a version called "w/ still mode" which supposedly suppresses facial movements, and I want to install it immediately, but I couldn't find that command in the readme.

I don't know whether to add "w/ still mode" to "-expression_scale" or to the "--enhancer" section, and I don't know how to describe it, since there is no explanation of how to do so.

**Comment by yablokoff** [comment]
It's right in the inference.py, https://github.com/Winfredy/SadTalker/blob/main/inference.py#L108
Just add a `--still` flag when you run inference.py
