### ISSUE TITLE
ubuntu Building llvmlite requires LLVM 7.0+ Be sure to set LLVM_CONFIG to the right executable path.

### ISSUE THREAD

**Issue by johndpope** [Winfredy/SadTalker#45]
Requirement already satisfied: contourpy>=1.0.1 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from matplotlib->filterpy->facexlib==0.2.5->-r requirements3d.txt (line 17)) (1.0.6)
Requirement already satisfied: python-dateutil>=2.7 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from matplotlib->filterpy->facexlib==0.2.5->-r requirements3d.txt (line 17)) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from matplotlib->filterpy->facexlib==0.2.5->-r requirements3d.txt (line 17)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from matplotlib->filterpy->facexlib==0.2.5->-r requirements3d.txt (line 17)) (4.38.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from requests->basicsr==1.4.2->-r requirements3d.txt (line 16)) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from requests->basicsr==1.4.2->-r requirements3d.txt (line 16)) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from requests->basicsr==1.4.2->-r requirements3d.txt (line 16)) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from requests->basicsr==1.4.2->-r requirements3d.txt (line 16)) (1.26.13)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from tb-nightly->basicsr==1.4.2->-r requirements3d.txt (line 16)) (1.8.1)
Requirement already satisfied: markdown>=2.6.8 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from tb-nightly->basicsr==1.4.2->-r requirements3d.txt (line 16)) (3.4.1)
Requirement already satisfied: protobuf<4,>=3.9.2 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from tb-nightly->basicsr==1.4.2->-r requirements3d.txt (line 16)) (3.20.0)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from tb-nightly->basicsr==1.4.2->-r requirements3d.txt (line 16)) (0.6.1)
Requirement already satisfied: absl-py>=0.4 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from tb-nightly->basicsr==1.4.2->-r requirements3d.txt (line 16)) (1.3.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from tb-nightly->basicsr==1.4.2->-r requirements3d.txt (line 16)) (2.14.1)
Requirement already satisfied: werkzeug>=1.0.1 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from tb-nightly->basicsr==1.4.2->-r requirements3d.txt (line 16)) (2.2.2)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from tb-nightly->basicsr==1.4.2->-r requirements3d.txt (line 16)) (0.4.6)
Requirement already satisfied: grpcio>=1.24.3 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from tb-nightly->basicsr==1.4.2->-r requirements3d.txt (line 16)) (1.50.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tb-nightly->basicsr==1.4.2->-r requirements3d.txt (line 16)) (0.2.8)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tb-nightly->basicsr==1.4.2->-r requirements3d.txt (line 16)) (5.2.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tb-nightly->basicsr==1.4.2->-r requirements3d.txt (line 16)) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tb-nightly->basicsr==1.4.2->-r requirements3d.txt (line 16)) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from markdown>=2.6.8->tb-nightly->basicsr==1.4.2->-r requirements3d.txt (line 16)) (5.1.0)
Requirement already satisfied: zipp>=0.5 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tb-nightly->basicsr==1.4.2->-r requirements3d.txt (line 16)) (3.11.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tb-nightly->basicsr==1.4.2->-r requirements3d.txt (line 16)) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tb-nightly->basicsr==1.4.2->-r requirements3d.txt (line 16)) (3.2.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages (from werkzeug>=1.0.1->tb-nightly->basicsr==1.4.2->-r requirements3d.txt (line 16)) (2.1.1)
Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/oem/miniconda3/envs/ldm2/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mi8t38g9/llvmlite_989da752628c422a8009813d14822a81/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mi8t38g9/llvmlite_989da752628c422a8009813d14822a81/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-8kcoad95
       cwd: /tmp/pip-install-mi8t38g9/llvmlite_989da752628c422a8009813d14822a81/
  Complete output (16 lines):
  running bdist_wheel
  /home/oem/miniconda3/envs/ldm2/bin/python /tmp/pip-install-mi8t38g9/llvmlite_989da752628c422a8009813d14822a81/ffi/build.py
  LLVM version... llvm-config: /home/oem/miniconda3/lib/libtinfo.so.6: no version information available (required by llvm-config)
  14.0.0
  
  Traceback (most recent call last):
    File "/tmp/pip-install-mi8t38g9/llvmlite_989da752628c422a8009813d14822a81/ffi/build.py", line 168, in <module>
      main()
    File "/tmp/pip-install-mi8t38g9/llvmlite_989da752628c422a8009813d14822a81/ffi/build.py", line 158, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-mi8t38g9/llvmlite_989da752628c422a8009813d14822a81/ffi/build.py", line 120, in main_posix
      raise RuntimeError(msg)
  RuntimeError: Building llvmlite requires LLVM 7.0+ Be sure to set LLVM_CONFIG to the right executable path.
  Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
  
  error: command '/home/oem/miniconda3/envs/ldm2/bin/python' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite, scipy, numba, joblib, imageio, scikit-image, resampy, yacs, trimesh, librosa, kornia, imageio-ffmpeg, face-alignment, dlib-bin
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.39.1
    Uninstalling llvmlite-0.39.1:
      Successfully uninstalled llvmlite-0.39.1
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /home/oem/miniconda3/envs/ldm2/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mi8t38g9/llvmlite_989da752628c422a8009813d14822a81/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mi8t38g9/llvmlite_989da752628c422a8009813d14822a81/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ochopfnf/install-record.txt --single-version-externally-managed --compile --install-headers /home/oem/miniconda3/envs/ldm2/include/python3.9/llvmlite
         cwd: /tmp/pip-install-mi8t38g9/llvmlite_989da752628c422a8009813d14822a81/
    Complete output (21 lines):
    running install
    /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    got version from file /tmp/pip-install-mi8t38g9/llvmlite_989da752628c422a8009813d14822a81/llvmlite/_version.py {'version': '0.31.0', 'full': 'fe7d985f6421d87f613bd414479d29d912771562'}
    running build_ext
    /home/oem/miniconda3/envs/ldm2/bin/python /tmp/pip-install-mi8t38g9/llvmlite_989da752628c422a8009813d14822a81/ffi/build.py
    LLVM version... llvm-config: /home/oem/miniconda3/lib/libtinfo.so.6: no version information available (required by llvm-config)
    14.0.0
    
    Traceback (most recent call last):
      File "/tmp/pip-install-mi8t38g9/llvmlite_989da752628c422a8009813d14822a81/ffi/build.py", line 168, in <module>
        main()
      File "/tmp/pip-install-mi8t38g9/llvmlite_989da752628c422a8009813d14822a81/ffi/build.py", line 158, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-mi8t38g9/llvmlite_989da752628c422a8009813d14822a81/ffi/build.py", line 120, in main_posix
        raise RuntimeError(msg)
    RuntimeError: Building llvmlite requires LLVM 7.0+ Be sure to set LLVM_CONFIG to the right executable path.
    Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
    
    error: command '/home/oem/miniconda3/envs/ldm2/bin/python' failed with exit code 1
    ----------------------------------------
  Rolling back uninstall of llvmlite
  Moving to /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages/llvmlite
   from /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages/~lvmlite
  Moving to /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages/llvmlite-0.39.1-py3.9.egg-info
   from /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages/~lvmlite-0.39.1-py3.9.egg-info
ERROR: Command errored out with exit status 1: /home/oem/miniconda3/envs/ldm2/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mi8t38g9/llvmlite_989da752628c422a8009813d14822a81/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mi8t38g9/llvmlite_989da752628c422a8009813d14822a81/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ochopfnf/install-record.txt --single-version-externally-managed --compile --install-headers /home/oem/miniconda3/envs/ldm2/include/python3.9/llvmlite Check the logs for full command output.

UPDATE 

```shell
sudo apt-get install libllvm-14-ocaml-dev libllvm14 llvm-14 llvm-14-dev llvm-14-doc llvm-14-examples llvm-14-runtime
```

and I update .zshrc
```shell
export LD_LIBRARY_PATH=$HOME/.miniconda3/envs/ldm2/lib:$LD_LIBRARY_PATH
export LLVM_CONFIG=/usr/bin/llvm-config-14
```

but no joy.

Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite, scipy, numba, joblib, imageio, scikit-image, resampy, yacs, trimesh, librosa, kornia, imageio-ffmpeg, face-alignment, dlib-bin
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.39.1
    Uninstalling llvmlite-0.39.1:
      Successfully uninstalled llvmlite-0.39.1
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /home/oem/miniconda3/envs/ldm2/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9jv2q5m2/llvmlite_ddde0f598ad9469b92939673cd0b4f4e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9jv2q5m2/llvmlite_ddde0f598ad9469b92939673cd0b4f4e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ubj4g4b4/install-record.txt --single-version-externally-managed --compile --install-headers /home/oem/miniconda3/envs/ldm2/include/python3.9/llvmlite
         cwd: /tmp/pip-install-9jv2q5m2/llvmlite_ddde0f598ad9469b92939673cd0b4f4e/
    Complete output (20 lines):
    running install
    /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    got version from file /tmp/pip-install-9jv2q5m2/llvmlite_ddde0f598ad9469b92939673cd0b4f4e/llvmlite/_version.py {'version': '0.31.0', 'full': 'fe7d985f6421d87f613bd414479d29d912771562'}
    running build_ext
    /home/oem/miniconda3/envs/ldm2/bin/python /tmp/pip-install-9jv2q5m2/llvmlite_ddde0f598ad9469b92939673cd0b4f4e/ffi/build.py
    LLVM version... 14.0.0
    
    Traceback (most recent call last):
      File "/tmp/pip-install-9jv2q5m2/llvmlite_ddde0f598ad9469b92939673cd0b4f4e/ffi/build.py", line 168, in <module>
        main()
      File "/tmp/pip-install-9jv2q5m2/llvmlite_ddde0f598ad9469b92939673cd0b4f4e/ffi/build.py", line 158, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-9jv2q5m2/llvmlite_ddde0f598ad9469b92939673cd0b4f4e/ffi/build.py", line 120, in main_posix
        raise RuntimeError(msg)
    RuntimeError: Building llvmlite requires LLVM 7.0+ Be sure to set LLVM_CONFIG to the right executable path.
    Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
    
    error: command '/home/oem/miniconda3/envs/ldm2/bin/python' failed with exit code 1
    ----------------------------------------
  Rolling back uninstall of llvmlite
  Moving to /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages/llvmlite
   from /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages/~lvmlite
  Moving to /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages/llvmlite-0.39.1-py3.9.egg-info
   from /home/oem/miniconda3/envs/ldm2/lib/python3.9/site-packages/~lvmlite-0.39.1-py3.9.egg-info
ERROR: Command errored out with exit status 1: /home/oem/miniconda3/envs/ldm2/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9jv2q5m2/llvmlite_ddde0f598ad9469b92939673cd0b4f4e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9jv2q5m2/llvmlite_ddde0f598ad9469b92939673cd0b4f4e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ubj4g4b4/install-record.txt --single-version-externally-managed --compile --install-headers /home/oem/miniconda3/envs/ldm2/include/python3.9/llvmlite Check the logs for full command output.

**pip install lvmlite** succeeds.

**Comment by vinthony** [comment]
I also update the newer version of the `requriements.txt`, where use newer number and librosa.
