### ISSUE TITLE
cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by cetiny** [Winfredy/SadTalker#48]
This is an excellent repo. Thank you for sharing. I am having the following issue with some of the image files. Tried saving as PNG, JPG, also saving on Photoshop without the ICC profile. No success. What can be the reason?

```
examples/source_image/yetinew3.png
./checkpoints/epoch_20.pth
./checkpoints/auido2pose_00140-model.pth
./checkpoints/auido2exp_00300-model.pth
./checkpoints/facevid2vid_00189-model.pth.tar
./checkpoints/mapping_00229-model.pth.tar
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "inference.py", line 132, in <module>
    main(args)
  File "inference.py", line 64, in main
    first_coeff_path, crop_pic_path, original_size =  preprocess_model.generate(pic_path, first_frame_dir, args.preprocess)
  File "/content/SadTalker/src/utils/preprocess.py", line 85, in generate
    x_full_frames, crop, quad = self.croper.crop(x_full_frames, xsize=pic_size)
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by vinthony** [comment]
this link may helpful: https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile

**Comment by cetiny** [comment]
Thank you @vinthony . The iCCP issue is resolved but still getting the following error. Do you have another idea? It is happening with different image files.

`TypeError: cannot unpack non-iterable NoneType object`

**Comment by pk5ls20** [comment]
I have same problem too

**Comment by vinthony** [comment]
similar to #68 , maybe the images do not contains the face where the face detector can detect.
