### ISSUE TITLE
real time talking head

### ISSUE THREAD

**Issue by seshubonam** [Winfredy/SadTalker#5]
hi, great work ! do you think this can work in realtime interactive scenarios. like talking that are love/interactive

**Comment by Winfredy** [comment]
Our work couldn't be used in realtime interactive scenarios. Because it still cost some time in video generation.

**Comment by vinthony** [comment]
> hi, great work ! do you think this can work in realtime interactive scenarios. like talking that are love/interactive

Hi, you might try to optimize the facerender using [TensorRT](https://github.com/NVIDIA/TensorRT), which might be helpful for speed up.

**Comment by seshubonam** [comment]
> Our work couldn't be used in realtime interactive scenarios. Because it still cost some time in video generation.

do you think a more powerful gpu could make it realtime application, like live interaction with talking head

**Comment by smtabatabaie** [comment]
Hi @seshubonam , Could you find any solutions with this? with Sadtalker or any other methods
