### ISSUE TITLE
抖动如何消除

### ISSUE THREAD

**Issue by LabEnbug** [Winfredy/SadTalker#55]
作者你好，生成的视频有抖动，肩膀比较明显，请问这个应该如何消除？

**Comment by Winfredy** [comment]
这个主要是facerender部分expression 和 pose没有完全解耦导致的，后续我们解决掉这个问题后会第一时间更新

**Comment by Yunlong-He** [comment]
没有完全解耦的原因是什么呢？

**Comment by Winfredy** [comment]
可能是使用的训练数据太少了。
