### ISSUE TITLE
error message：“cv2.error: OpenCV(4.7.0) /io/opencv/modules/core/src/matrix.cpp:808”

### ISSUE THREAD

**Issue by Benny101219** [Winfredy/SadTalker#57]
when i run the command：
python3 inference.py --driven_audio /home/aigc/digital/data/04-03_voice.wav    --source_image  /home/aigc/digital/data/00001-4058931191.png   --result_dir  ./output   --still   --enhancer gfpgan  --full_img_enhancer gfpgan

the error message as follow：

[aac @ 0x559fd65eeca0] Qavg: 43767.578
The generated video is named 00001-4058931191##04-03_voice_enhanced.mp4 in ./output/2023_04_04_00.26.07
uint8
seamlessClone::   0%|                                                                                                                                                                                              | 0/983 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/aigc/digital/SadTalker/inference.py", line 154, in <module>
    main(args)
  File "/home/aigc/digital/SadTalker/inference.py", line 108, in main
    animate_from_coeff.generate(data, save_dir, pic_path, crop_info, \
  File "/home/aigc/digital/SadTalker/src/facerender/animate.py", line 205, in generate
    paste_pic(av_path_enhancer, pic_path, crop_info, new_audio_path, full_video_path)
  File "/home/aigc/digital/SadTalker/src/utils/paste_pic.py", line 40, in paste_pic
    gen_img = cv2.seamlessClone(p, full_img, mask, location, cv2.NORMAL_CLONE)
cv2.error: OpenCV(4.7.0) /io/opencv/modules/core/src/matrix.cpp:808: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'Mat'

**Comment by Benny101219** [comment]
the image size is 512x1024

**Comment by Anonym0us33** [comment]
```python inference.py --driven_audio "AUDIOS/output0.wav"  --source_image picture.png  --result_dir results ^
    --still ^
    --enhancer gfpgan ^
    --full_img_enhancer gfpgan
```
```gen_img = cv2.seamlessClone(p, full_img, mask, location, cv2.NORMAL_CLONE)
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\matrix.cpp:809: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'cv::Mat::Mat'```

**Comment by Anonym0us33** [comment]
pip list:
Package                 Version
----------------------- ---------------
absl-py                 1.4.0
addict                  2.4.0
aiofiles                23.1.0
aiohttp                 3.8.4
aiosignal               1.3.1
altair                  4.2.2
anyio                   3.6.2
async-timeout           4.0.2
attrs                   22.2.0
audioread               3.0.0
basicsr                 1.4.2
cachetools              5.3.0
certifi                 2022.12.7
cffi                    1.15.1
charset-normalizer      2.1.1
click                   8.1.3
colorama                0.4.6
contourpy               1.0.7
cycler                  0.11.0
decorator               5.1.1
dlib                    19.24.1
dlib-bin                19.24.1
entrypoints             0.4
face-alignment          1.3.5
facexlib                0.2.5
fastapi                 0.95.0
ffmpy                   0.3.0
filelock                3.10.7
filterpy                1.4.5
fonttools               4.39.3
frozenlist              1.3.3
fsspec                  2023.3.0
future                  0.18.3
gfpgan                  1.3.8
google-auth             2.17.1
google-auth-oauthlib    1.0.0
gradio                  3.24.1
gradio_client           0.0.5
grpcio                  1.53.0
h11                     0.14.0
httpcore                0.16.3
httpx                   0.23.3
huggingface-hub         0.13.3
idna                    3.4
imageio                 2.19.3
imageio-ffmpeg          0.4.7
importlib-metadata      6.1.0
importlib-resources     5.12.0
Jinja2                  3.1.2
joblib                  1.1.0
jsonschema              4.17.3
kiwisolver              1.4.4
kornia                  0.6.8
librosa                 0.9.2
linkify-it-py           2.0.0
llvmlite                0.31.0
lmdb                    1.4.0
Markdown                3.4.3
markdown-it-py          2.2.0
MarkupSafe              2.1.2
matplotlib              3.7.1
mdit-py-plugins         0.3.3
mdurl                   0.1.2
mpmath                  1.3.0
multidict               6.0.4
networkx                3.0
numba                   0.48.0
numpy                   1.23.4
oauthlib                3.2.2
opencv-python           4.7.0.72
orjson                  3.8.9
packaging               23.0
pandas                  2.0.0
Pillow                  9.5.0
pip                     23.0.1
pkgutil_resolve_name    1.3.10
platformdirs            3.2.0
pooch                   1.7.0
protobuf                4.22.1
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycparser               2.21
pydantic                1.10.7
pydub                   0.25.1
pyparsing               3.0.9
pyrsistent              0.19.3
python-dateutil         2.8.2
python-multipart        0.0.6
pytz                    2023.3
PyWavelets              1.4.1
PyYAML                  6.0
requests                2.28.1
requests-oauthlib       1.3.1
resampy                 0.3.1
rfc3986                 1.5.0
rsa                     4.9
scikit-image            0.19.3
scikit-learn            1.1.3
scipy                   1.5.3
semantic-version        2.10.0
setuptools              49.2.1
six                     1.16.0
sniffio                 1.3.0
soundfile               0.12.1
starlette               0.26.1
sympy                   1.11.1
tb-nightly              2.13.0a20230403
tensorboard-data-server 0.7.0
tensorboard-plugin-wit  1.8.1
threadpoolctl           3.1.0
tifffile                2023.3.21
toolz                   0.12.0
torch                   2.0.0+cu117
torchaudio              2.0.1+cu117
torchvision             0.15.1+cu117
tqdm                    4.65.0
trimesh                 3.9.20
typing_extensions       4.5.0
tzdata                  2023.3
uc-micro-py             1.0.1
urllib3                 1.26.13
uvicorn                 0.21.1
websockets              11.0
Werkzeug                2.2.3
wheel                   0.40.0
yacs                    0.1.8
yapf                    0.32.0
yarl                    1.8.2
zipp                    3.15.0

python -V
Python 3.8.7

nvcc --version
Build cuda_11.6.r11.6/compiler.31057947_0

nvidia-smi
Tue Apr  4 07:47:04 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 472.12       Driver Version: 472.12       CUDA Version: 11.4     |

**Comment by Benny101219** [comment]
i have resolved the issue, change the png image to jpg image.

**Comment by vinthony** [comment]
it seems that the error was caused by seamless clone We will try to fix this issue

**Comment by syguan96** [comment]
[Help] Have you solved this problem? @Benny101219 @vinthony
