### ISSUE TITLE
there might be an issue with the installation of gfpgan provided in your script

### ISSUE THREAD

**Issue by yzxyzh** [Winfredy/SadTalker#59]
this is what you are providing:
### install gpfgan for enhancer
pip install git+https://github.com/TencentARC/GFPGAN

I think it should be:
### install gpfgan for enhancer
pip install git+https://github.com/TencentARC/GFPGAN.git

since I failed to run the original command.

**Comment by vinthony** [comment]
thanks for your contribution and we will correct this! we also find we can directly install gfpgan via `pip install gfpgan`, which might be much easier.
