### ISSUE TITLE
running inference got error

### ISSUE THREAD

**Issue by jackleibest** [Winfredy/SadTalker#60]
hi, nice work, i just download the trained models from github. then I try the prefence, got the following errors:
![微信截图_20230406112513](https://user-images.githubusercontent.com/56916962/230264776-cfb5047e-4f2c-444e-a49e-81874e03c8b9.png)
so, what's the problem? my pytorch version is:
torch                        1.12.0+cu113
torchaudio                   0.12.0+cu113
torchmetrics                 0.11.3
torchvision                  0.13.0+cu113

**Comment by Winfredy** [comment]
Did you download the model successfully? It seems that you didn't download the facevid2vid model completely. The size of facevid2vid model is about 1.96 GB.

**Comment by jackleibest** [comment]
yeah, however, i download the models successfully, and got the error:
![微信截图_20230406143423](https://user-images.githubusercontent.com/56916962/230291446-aebfce39-4292-463d-adf1-705d07161563.png)
and the python version is: 
Python 3.9.13
numba   0.49.1
llvmlite  0.32.1
librosa   0.9.2

**Comment by jackleibest** [comment]
just removig --enhancer, and it is not working either.

**Comment by vinthony** [comment]
try to follow the details from https://github.com/Winfredy/SadTalker#dependence-installation

**Comment by johndpope** [comment]
N.b  this could use a version bump - we're up to (stable) cuda11.8 now. 

pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113

**Comment by vinthony** [comment]
no response for a long time, closed
