### ISSUE TITLE
在使用的时候，有时候生成的MP4，图片没有动。

### ISSUE THREAD

**Issue by muchenlou** [Winfredy/SadTalker#62]
可能是模型的问题

**Comment by vinthony** [comment]
有例子吗

**Comment by muchenlou** [comment]
> 有例子吗

我使用我女朋友的照片。就眉毛在动

**Comment by vinthony** [comment]
使用方式：https://github.com/Winfredy/SadTalker/blob/main/docs/best_practice.md

**Comment by muchenlou** [comment]
> 使用方式：https://github.com/Winfredy/SadTalker/blob/main/docs/best_practice.md

哈哈哈，你们更新太快了，我应该使用哪一个版本进行二开呀（我要加入API，进行API调用。）

**Comment by vinthony** [comment]
目前的版本比较稳定

**Comment by muchenlou** [comment]
> 目前的版本比较稳定

好的。

**Comment by muchenlou** [comment]
> 目前的版本比较稳定

大佬，怎么我按照安装步骤在linux 安装，没用到GPU呢？
 print(torch.cuda.is_available())
为False

**Comment by vinthony** [comment]
这个是基础pytorch的问题，建议google

**Comment by vinthony** [comment]
> > 使用方式：https://github.com/Winfredy/SadTalker/blob/main/docs/best_practice.md
> 
> 哈哈哈，你们更新太快了，我应该使用哪一个版本进行二开呀（我要加入API，进行API调用。）

仔细看readme，注意不能商用哦。
