### ISSUE TITLE
透明背景的图片合成视频后，背景变成黑色了

### ISSUE THREAD

**Issue by nicholaspei** [Winfredy/SadTalker#67]
使用一个透明背景的图片+一段音频合成视频后，发现背景变成黑色了，大概原因是从RGB转成BGR格式时丢掉了alpha通道，有么有哪位大佬提供一个思路解决这个问题。

**Comment by vinthony** [comment]
先用白色底图合成视频之后，再抠图？

**Comment by nicholaspei** [comment]
> 

也是个办法。我试试。thanks！

**Comment by nicholaspei** [comment]
果然可行。。先生称抠图后的PNG图片，然后把图片覆盖到一个视频上就行了。

**Comment by mindbugg** [comment]
面对同样的问题，我打算使用带有 alpha 通道的图像，并添加绿色背景或图像。但它总是变黑。
根据您的建议“先将视频与白色底图合成后，再剪切图像？”

我怎样才能剪切渲染的视频。请指教。谢谢
