### ISSUE TITLE
Major problem with Sad Talker

### ISSUE THREAD

**Issue by Harsh-raj** [Winfredy/SadTalker#709]
Kudos to the creators, but I still can't figure it out why sadTalker was created with such an ancient version of pytorch, torchvision and torchaudio. This older version denies any attempt to utilise this model with any other existing technologies. If some solution to this problem is available please let me know. Also If there are alternatives to this model available that I am unaware of please let me know i would be greatful.

**Comment by rachit2315** [comment]
### There are a few open-source models that can be used for creating talking avatars similar to Sad Talker. Some of the most promising options include:
"**DeepFaceLab**" - an open-source tool for face swapping that can be used to create realistic talking avatars.
"**PoseNet**" - a deep learning model that can detect human poses from images, which can be used to animate an avatar.
"**GANs**" (Generative Adversarial Networks) - a type of AI model that can generate new images or videos based on a training set. This can be used to create talking avatars that look realistic and move in a natural way.
These tools require some technical know-how to use, but they offer a lot of flexibility and can produce high-quality results.
