### ISSUE TITLE
Generate realtime video WEBRTC

### ISSUE THREAD

**Issue by sunilsingh2019** [Winfredy/SadTalker#723]
Hey pals, hope you're doing well! I could really use your help with something. I'm trying to figure out how to make videos in real-time, and I'm thinking of using WebRTC. Any advice on making sure the videos generate smoothly without any hiccups? Your assistance would mean a lot to me. Thanks a bunch!

**Comment by chinarui-na** [comment]
+1

**Comment by newpepsi** [comment]
How fast do you generate the video?

**Comment by sunilsingh2019** [comment]
> How fast do you generate the video?
Hey I am looking live streaming do you know any solution for this ?

**Comment by nitinmukesh** [comment]
@sunilsingh2019 You can refer this for real time diffusion
https://www.youtube.com/watch?v=WaNd9WT6yCI

**Comment by alokraj68** [comment]
@sunilsingh2019  where you able to get it done?
What was the gpu you needed to do this?
