### ISSUE TITLE
Whoever can solve my problem is a genius

### ISSUE THREAD

**Issue by Dreamnftx** [Winfredy/SadTalker#725]
**I'm not sure if I'm going to be able to do this, but I'm not sure if I'm going to be able to do this, but I'm not sure if I'm going to be able to do this, but I'm not sure if I'm going to be able to do this. I put you the code to see what you think ChatGPT but help but I understood nothing if someone can help me step by step it would be cool :)**

IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (256, 250) to (256, 256) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
The generated video is named ./results/6f342887-6cd1-4c86-be51-c646f9037b39/art_6##fayu.mp4
The generated video is named art_6##fayu in ./results/6f342887-6cd1-4c86-be51-c646f9037b39
ffmpeg version 6.1-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --pkg-config=pkgconf --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './results/6f342887-6cd1-4c86-be51-c646f9037b39\art_6##fayu.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.16.100
  Duration: 00:00:06.72, start: 0.000000, bitrate: 212 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 256x256, 97 kb/s, 25 fps, 25 tbr, 12800 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, stereo, fltp, 107 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Output ./results/6f342887-6cd1-4c86-be51-c646f9037b39\art_6##fayu.mp4 same as Input #0 - exiting
FFmpeg cannot edit existing files in-place.
Error opening output file ./results/6f342887-6cd1-4c86-be51-c646f9037b39\art_6##fayu.mp4.
Error opening output files: Invalid argument
Traceback (most recent call last):
  File "C:\Users\oudih\Desktop\test\SadTalker\venv\lib\site-packages\gradio\queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\oudih\Desktop\test\SadTalker\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\oudih\Desktop\test\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1531, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\oudih\Desktop\test\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1420, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\oudih\Desktop\test\SadTalker\venv\lib\site-packages\gradio\components\video.py", line 222, in postprocess
    processed_files = (self._format_video(y), None)
  File "C:\Users\oudih\Desktop\test\SadTalker\venv\lib\site-packages\gradio\components\video.py", line 291, in _format_video
    ff.run()
  File "C:\Users\oudih\Desktop\test\SadTalker\venv\lib\site-packages\ffmpy.py", line 113, in run
    raise FFRuntimeError(self.cmd, self.process.returncode, out[0], out[1])
ffmpy.FFRuntimeError: `ffmpeg -y -i ./results/6f342887-6cd1-4c86-be51-c646f9037b39\art_6##fayu.mp4 ./results/6f342887-6cd1-4c86-be51-c646f9037b39\art_6##fayu.mp4` exited with status 4294967274

STDOUT:

STDERR:

Traceback (most recent call last):
  File "C:\Users\oudih\Desktop\test\SadTalker\venv\lib\site-packages\gradio\queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\oudih\Desktop\test\SadTalker\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\oudih\Desktop\test\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1531, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\oudih\Desktop\test\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1420, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\oudih\Desktop\test\SadTalker\venv\lib\site-packages\gradio\components\video.py", line 222, in postprocess
    processed_files = (self._format_video(y), None)
  File "C:\Users\oudih\Desktop\test\SadTalker\venv\lib\site-packages\gradio\components\video.py", line 291, in _format_video
    ff.run()
  File "C:\Users\oudih\Desktop\test\SadTalker\venv\lib\site-packages\ffmpy.py", line 113, in run
    raise FFRuntimeError(self.cmd, self.process.returncode, out[0], out[1])
ffmpy.FFRuntimeError: `ffmpeg -y -i ./results/6f342887-6cd1-4c86-be51-c646f9037b39\art_6##fayu.mp4 ./results/6f342887-6cd1-4c86-be51-c646f9037b39\art_6##fayu.mp4` exited with status 4294967274

STDOUT:

STDERR:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oudih\Desktop\test\SadTalker\venv\lib\site-packages\gradio\queueing.py", line 501, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "C:\Users\oudih\Desktop\test\SadTalker\venv\lib\site-packages\gradio\queueing.py", line 465, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None

![Capture d'écran 2023-11-30 042418](https://github.com/OpenTalker/SadTalker/assets/152450934/9ad9a032-63fc-46c6-b9d4-a0553136400b)

**Config :**
 - NVIDIA GeForce GTX 1660 SUPER 
 - AMD Ryzen 5 3500X 6-Core Processor

**Solution by ChatGPT :**

The error message indicates that the video processing tool (FFmpeg) is encountering a problem when generating the video from the image and audio you are trying to combine. The specific part of the error is as follows:

bash
Copy code
Error opening output file ./results/fe019606-de88-413b-9ca3-c22e107a2e17\art_6##fayu.mp4.
Error opening output files: Invalid argument
This indicates that FFmpeg is having difficulty opening or creating the output file. Here are some suggestions for resolving this problem:

Check Permissions : Make sure that the user running the script has the necessary permissions to write to the specified directory (./results/fe019606-de88-413b-9ca3-c22e107a2e17/). You could try changing the directory permissions if necessary.

Output File Path: Make sure that the output file path is correct and that the directory exists. You can also try simplifying the path by using a filename without special characters or spaces.

Existing Files: Make sure that there is not already a file with the same name as the one you are trying to create. FFmpeg cannot overwrite an existing file by default.

Disk Space Problems: Check that there is sufficient disk space on your system to create the output file.

Try these steps to see if they solve the problem. If the problem persists, you might also consider consulting the Gradio or FFmpeg documentation, or asking for help on the technical support forums associated with these tools.

**Comment by ZainA-Official** [comment]
Make sure you have FFmpeg installed, it's a separate installation not done through pip. I think the file _did_ generate though so you should find it in the results/....../art_6##fay.mp4 . Gradio just isn't outputting it.

**Comment by msmr23** [comment]
I have the same problem, any solution?

**Comment by Dreamnftx** [comment]
@Simmer1234569 Yes, FFmeg is installed on my hard disk /Windows (C:)/ But it's not in the SadTalker file - should I put it in there or not at all? Do you think there's a solution to my problem or can I just get the results from gradio in the folder called "Result"? And I wanted to have your "FFmpeg" file if you could send it to me that would be great and once you've sent it to me should I modify the variable environment again?

**Comment by Dreamnftx** [comment]
If it helps, I don't know what to do, I'm lost :'( Maybe I don't have the right version of FFMEG, what do you think? @Simmer1234569 

![image](https://github.com/OpenTalker/SadTalker/assets/152450934/9b5a4652-c217-4cc8-8f60-7a7c0baaec23)
![Capture d'écran 2023-12-01 210940](https://github.com/OpenTalker/SadTalker/assets/152450934/0f8fb5d1-d83d-4fcd-a957-bace82f9f061)

**Comment by srkn0** [comment]
same issue here

**Comment by msmr23** [comment]
the problem is in the line of code, you have to be a good expert to understand, the only way that worked for me was in stable diffusion, I haven't found anything so far, in independence

**Comment by srkn0** [comment]
> the problem is in the line of code, you have to be a good expert to understand, the only way that worked for me was in stable diffusion, I haven't found anything so far, in independence

i tried sadtalker as stable diffusion extension today, it works perfectly fine! thx

**Comment by Dreamnftx** [comment]
Hi @srkn0 Can you tell us how you do it?

**Comment by srkn0** [comment]
> Hi @srkn0 Can you tell us how you do it?


follow the instructions for stable diffusion webui installation on this repo:

https://github.com/AUTOMATIC1111/stable-diffusion-webui

after successful installation switch to this guide for the sadtalker extension 

https://github.com/OpenTalker/SadTalker/blob/main/docs/webui_extension.md

**Comment by Yacine75005** [comment]
Ok problem solved, I leave my discussion open for those who have the same problem fortunately there is @srkn0  who gave us the solution thank you all for your participation including @Simmer1234569 too <3 <3

**Comment by Dreamnftx** [comment]
Ok problème résolu, je laisse ma discussion ouverte pour ceux qui ont le même problème heureusement qu'il y en a@srkn0 qui nous a donné la solution merci à tous pour votre participation notamment@Simmer1234569aussi <3 <3

**Comment by viccP** [comment]
看起来这是一个bug，报错的原因是ffmpeg转换前和转换后的文件是同一个，需要修改一下相应源码才可以。
traslate：It looks like there's a bug, and the error is occurring because ffmpeg is using the same file before and after conversion. You need to make modifications to the corresponding source code to fix this issue.

![image](https://github.com/OpenTalker/SadTalker/assets/11806067/071ea81c-901a-4dbb-ab84-7ec4c4e36a15)

#734  's solution works

**Comment by Globalteamspeak** [comment]
I solved this by replacing gradio with gradio==4.1.1 in requirements.txt
