### ISSUE TITLE
Issue with automatic plugin install

### ISSUE THREAD

**Issue by bbecausereasonss** [Winfredy/SadTalker#73]
Received errors during install:

face-alignment False
Installing requirements for SadTalker
imageio True
imageio-ffmpeg False
Installing requirements for SadTalker
librosa True
pydub True
scipy True
tqdm True
yacs True
pyyaml False
Installing requirements for SadTalker
dlib True
gfpgan True
load Sadtalker Checkpoints from C:\Users\xxx\Deep\SadTalker\checkpoints

**Comment by vinthony** [comment]
any other error reported?

**Comment by bbecausereasonss** [comment]
During initial install there was an error that halted the full installation, I cannot recall what it is right now I think it may have been torch related?

**Comment by vinthony** [comment]
similar to #78
