### ISSUE TITLE
error with --enhancer gfpgan

### ISSUE THREAD

**Issue by masoningithub** [Winfredy/SadTalker#74]
hi i'm getting below error when add --enhancer gfpganm, any idea why this happened and how to fix this?

The generated video is named 1##audio.mp4 in G:\test\2023_04_09_00.15.30
Traceback (most recent call last):
  File "inference.py", line 158, in <module>
    main(args)
  File "inference.py", line 112, in main
    animate_from_coeff.generate(data, save_dir, pic_path, crop_info, \
  File "G:\SadTalker\src\facerender\animate.py", line 200, in generate
    enhanced_images = face_enhancer(full_video_path, method=enhancer, bg_upsampler=background_enhancer)
UnboundLocalError: local variable 'full_video_path' referenced before assignment

**Comment by vinthony** [comment]
fixed in the most recent update
