### ISSUE TITLE
webui中开启 GFPGAN as Face enhancer 导致最终输出文件报错

### ISSUE THREAD

**Issue by newpepsi** [Winfredy/SadTalker#743]
Face Renderer:: 100%|██████████| 280/280 [01:21<00:00,  3.42it/s]
The generated video is named ./results/5b871c6e-689d-4542-ab2d-437e107263d8/1000##output2.mp4
seamlessClone:: 100%|██████████| 559/559 [00:54<00:00, 10.27it/s]
The generated video is named ./results/5b871c6e-689d-4542-ab2d-437e107263d8/1000##output2_full.mp4
face enhancer....
Face Enhancer::   0%|          | 0/559 [00:00<?, ?it/s]IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (1280, 1672) to (1280, 1680) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
Face Enhancer:: 100%|██████████| 559/559 [03:24<00:00,  2.74it/s]
The generated video is named ./results/5b871c6e-689d-4542-ab2d-437e107263d8/1000##output2_enhanced.mp4
The generated video is named 1000##output2 in ./results/5b871c6e-689d-4542-ab2d-437e107263d8
ffmpeg version 2023-12-04-git-8c117b75af-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --pkg-config=pkgconf --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58. 32.100 / 58. 32.100
  libavcodec     60. 35.100 / 60. 35.100
  libavformat    60. 18.100 / 60. 18.100
  libavdevice    60.  4.100 / 60.  4.100
  libavfilter     9. 14.100 /  9. 14.100
  libswscale      7.  6.100 /  7.  6.100
  libswresample   4. 13.100 /  4. 13.100
  libpostproc    57.  4.100 / 57.  4.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './results/5b871c6e-689d-4542-ab2d-437e107263d8\1000##output2_enhanced.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.18.100
  Duration: 00:00:22.36, start: 0.000000, bitrate: 1174 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1280x1680, 1096 kb/s, 25 fps, 25 tbr, 12800 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 72 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Output ./results/5b871c6e-689d-4542-ab2d-437e107263d8\1000##output2_enhanced.mp4 same as Input #0 - exiting
FFmpeg cannot edit existing files in-place.
Error opening output file ./results/5b871c6e-689d-4542-ab2d-437e107263d8\1000##output2_enhanced.mp4.
Error opening output files: Invalid argument
Traceback (most recent call last):
  File "C:\dev\SadTalker\venv\lib\site-packages\gradio\queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\dev\SadTalker\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\dev\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1531, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\dev\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1420, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\dev\SadTalker\venv\lib\site-packages\gradio\components\video.py", line 222, in postprocess
    processed_files = (self._format_video(y), None)
  File "C:\dev\SadTalker\venv\lib\site-packages\gradio\components\video.py", line 291, in _format_video
    ff.run()
  File "C:\dev\SadTalker\venv\lib\site-packages\ffmpy.py", line 113, in run
    raise FFRuntimeError(self.cmd, self.process.returncode, out[0], out[1])
ffmpy.FFRuntimeError: `ffmpeg -y -i ./results/5b871c6e-689d-4542-ab2d-437e107263d8\1000##output2_enhanced.mp4 ./results/5b871c6e-689d-4542-ab2d-437e107263d8\1000##output2_enhanced.mp4` exited with status 4294967274
STDOUT:
STDERR:
Traceback (most recent call last):
  File "C:\dev\SadTalker\venv\lib\site-packages\gradio\queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\dev\SadTalker\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\dev\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1531, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\dev\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1420, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\dev\SadTalker\venv\lib\site-packages\gradio\components\video.py", line 222, in postprocess
    processed_files = (self._format_video(y), None)
  File "C:\dev\SadTalker\venv\lib\site-packages\gradio\components\video.py", line 291, in _format_video
    ff.run()
  File "C:\dev\SadTalker\venv\lib\site-packages\ffmpy.py", line 113, in run
    raise FFRuntimeError(self.cmd, self.process.returncode, out[0], out[1])
ffmpy.FFRuntimeError: `ffmpeg -y -i ./results/5b871c6e-689d-4542-ab2d-437e107263d8\1000##output2_enhanced.mp4 ./results/5b871c6e-689d-4542-ab2d-437e107263d8\1000##output2_enhanced.mp4` exited with status 4294967274
STDOUT:
STDERR:
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\dev\SadTalker\venv\lib\site-packages\gradio\queueing.py", line 501, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "C:\dev\SadTalker\venv\lib\site-packages\gradio\queueing.py", line 465, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None

**Comment by newpepsi** [comment]
open  test_audio2coeff.py 
find line from 102 to 105 replace with the code blow  
```
savemat(os.path.join(coeff_save_dir, '%s_%s.mat'%(batch['pic_name'], batch['audio_name'])),
                    {'coeff_3dmm': coeffs_pred_numpy})

return os.path.join(coeff_save_dir, '%s_%s.mat'%(batch['pic_name'], batch['audio_name']))
```

**Comment by YexiongLin** [comment]
> open test_audio2coeff.py find line from 102 to 105 replace with the code blow
> 
> ```
> savemat(os.path.join(coeff_save_dir, '%s_%s.mat'%(batch['pic_name'], batch['audio_name'])),
>                     {'coeff_3dmm': coeffs_pred_numpy})
> 
> return os.path.join(coeff_save_dir, '%s_%s.mat'%(batch['pic_name'], batch['audio_name']))
> ```

It works. Thanks!

**Comment by lion1029** [comment]
savemat(os.path.join(coeff_save_dir, '%s_%s.mat'%(batch['pic_name'], batch['audio_name'])),
                    {'coeff_3dmm': coeffs_pred_numpy})

return os.path.join(coeff_save_dir, '%s_%s.mat'%(batch['pic_name'], batch['audio_name']))

It's worked for me! 
but there are some difference,
I opened the "test_audio2coeff.py", at line 102-105, there is no underline“_”between words, instead all the “_” are shown as space. so I **just replaced the ## to space**, 
Save, Bingo, It's working!

**Comment by brajendra304** [comment]
After replacing the solution in the test_audio2coeff.py file from line 102 to 105 with
savemat(os.path.join(coeff_save_dir, '%s_%s.mat'%(batch['pic_name'], batch['audio_name'])),
                    {'coeff_3dmm': coeffs_pred_numpy})

return os.path.join(coeff_save_dir, '%s_%s.mat'%(batch['pic_name'], batch['audio_name']))

Now i am not getting the error, but the program seems hanging there for more than 1 hour after generating ????_enhanced.mp4 file. Is it because ffmpeg takes much more time and my system is just i5 without any GPU. May be the original code in the ffile test_audio2coeff.py was deliberate so that program comes out with error for normal machines without GPU. Anyway the program is producing _full.mp4 and _enhanced.mp4 files. 

The last part of the command window where it seems like hanging for more than an hour is:
 
Face Enhancer:: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 73/73 [25:56<00:00, 21.32s/it]
The generated video is named ./results/8034d9f3-356f-4e9b-bfe5-05bda3d979bf/abcd_xyz_enhanced.mp4
The generated video is named abcd_xyz in ./results/8034d9f3-356f-4e9b-bfe5-05bda3d979bf
