### ISSUE TITLE
Got TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>. when I run it in stable diffusion UI

### ISSUE THREAD

**Issue by hLxiao9** [Winfredy/SadTalker#77]
When I drop the png and wav in the sadtalker tab in stable diffusion ui, and clicked generate, it processed for few seconds and raised an error:
Log:

> /Users/xiao9/Documents/AI/stable-diffusion-webui/extensions/SadTalker/checkpoints/shape_predictor_68_face_landmarks.dat
> Error verifying pickled file from /Users/xiao9/Documents/AI/stable-diffusion-webui/extensions/SadTalker/checkpoints/hub/checkpoints/s3fd-619a316812.pth:
> Traceback (most recent call last):
>   File "/Users/xiao9/Documents/AI/stable-diffusion-webui/modules/safe.py", line 81, in check_pt
>     with zipfile.ZipFile(filename) as z:
>   File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 1267, in __init__
>     self._RealGetContents()
>   File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 1334, in _RealGetContents
>     raise BadZipFile("File is not a zip file")
> zipfile.BadZipFile: File is not a zip file
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/xiao9/Documents/AI/stable-diffusion-webui/modules/safe.py", line 135, in load_with_extra
>     check_pt(filename, extra_handler)
>   File "/Users/xiao9/Documents/AI/stable-diffusion-webui/modules/safe.py", line 102, in check_pt
>     unpickler.load()
>   File "/Users/xiao9/Documents/AI/stable-diffusion-webui/modules/safe.py", line 62, in find_class
>     raise Exception(f"global '{module}/{name}' is forbidden")
> Exception: global 'torch._utils/_rebuild_tensor' is forbidden
> 
> 
> The file may be malicious, so the program is not going to read it.
> You can skip this check with --disable-safe-unpickle commandline argument.
> 
> 
> Traceback (most recent call last):
>   File "/Users/xiao9/Documents/AI/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
>     output = await app.get_blocks().process_api(
>   File "/Users/xiao9/Documents/AI/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1075, in process_api
>     result = await self.call_function(
>   File "/Users/xiao9/Documents/AI/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 884, in call_function
>     prediction = await anyio.to_thread.run_sync(
>   File "/Users/xiao9/Documents/AI/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "/Users/xiao9/Documents/AI/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
>     return await future
>   File "/Users/xiao9/Documents/AI/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
>     result = context.run(func, *args)
>   File "/Users/xiao9/Documents/AI/stable-diffusion-webui/modules/call_queue.py", line 15, in f
>     res = func(*args, **kwargs)
>   File "/Users/xiao9/Documents/AI/stable-diffusion-webui/extensions/SadTalker/src/gradio_demo.py", line 63, in test
>     self.preprocess_model = CropAndExtract(self.path_of_lm_croper, self.path_of_net_recon_model, self.dir_of_BFM_fitting, self.device)
>   File "/Users/xiao9/Documents/AI/stable-diffusion-webui/extensions/SadTalker/src/utils/preprocess.py", line 46, in __init__
>     self.kp_extractor = KeypointExtractor(device)
>   File "/Users/xiao9/Documents/AI/stable-diffusion-webui/extensions/SadTalker/src/face3d/extract_kp_videos.py", line 16, in __init__
>     self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, device=device)
>   File "/Users/xiao9/Documents/AI/stable-diffusion-webui/venv/lib/python3.10/site-packages/face_alignment/api.py", line 77, in __init__
>     self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose, **face_detector_kwargs)
>   File "/Users/xiao9/Documents/AI/stable-diffusion-webui/venv/lib/python3.10/site-packages/face_alignment/detection/sfd/sfd_detector.py", line 30, in __init__
>     self.face_detector.load_state_dict(model_weights)
>   File "/Users/xiao9/Documents/AI/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1559, in load_state_dict
>     raise TypeError("Expected state_dict to be dict-like, got {}.".format(type(state_dict)))
> TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.`

And that's the log when restarting the ui:

> Restarting UI...
> face-alignment False
> Installing requirements for SadTalker
> imageio True
> imageio-ffmpeg False
> Installing requirements for SadTalker
> librosa True
> pydub True
> scipy True
> tqdm True
> yacs True
> pyyaml False
> Installing requirements for SadTalker
> dlib True
> gfpgan True
> download models for SadTalker
> mkdir: ./checkpoints: File exists
> File './checkpoints/auido2exp_00300-model.pth' already there; not retrieving.
> File './checkpoints/auido2pose_00140-model.pth' already there; not retrieving.
> File './checkpoints/epoch_20.pth' already there; not retrieving.
> File './checkpoints/facevid2vid_00189-model.pth.tar' already there; not retrieving.
> File './checkpoints/shape_predictor_68_face_landmarks.dat' already there; not retrieving.
> File './checkpoints/wav2lip.pth' already there; not retrieving.
> File './checkpoints/mapping_00229-model.pth.tar' already there; not retrieving.
> File './checkpoints/BFM_Fitting.zip' already there; not retrieving.
> File './checkpoints/hub.zip' already there; not retrieving.
> Archive:  ./checkpoints/hub.zip
> Archive:  ./checkpoints/BFM_Fitting.zip
> SadTalker is successfully installed!

Can you please help? Thank you!

**Comment by vinthony** [comment]
`--disable-safe-unpickle` is needed as discussed in the readme in `webui_user.sh` as in the readme. We will find out how to avoid this.
<img width="900" alt="image" src="https://user-images.githubusercontent.com/4397546/230757265-ea01842c-5319-4f7e-9a4a-b2284696d45c.png">

**Comment by hLxiao9** [comment]
It works! Thank you.
