### ISSUE TITLE
Where to download mapping_00109-model.pth.tar

### ISSUE THREAD

**Issue by oldtreee** [Winfredy/SadTalker#79]
Where to download mapping_00109-model.pth.tar?
`FileNotFoundError: [Errno 2] No such file or directory: 'D:\\AItools\\stable-diffusion-webui\\extensions\\SadTalker\\checkpoints\\mapping_00109-model.pth.tar'`

**Comment by vinthony** [comment]
new release in v0.0.2: https://github.com/Winfredy/SadTalker/releases/download/v0.0.2/mapping_00109-model.pth.tar

**Comment by gongsikai1** [comment]
> new release in v0.0.2: https://github.com/Winfredy/SadTalker/releases/download/v0.0.2/mapping_00109-model.pth.tar

solved my problem
