### ISSUE TITLE
11

### ISSUE THREAD

**Issue by zhangnn520** [Winfredy/SadTalker#794]

**Comment by zhangnn520** [comment]
合成效果，现在支持图片和视频生成，我基于作者项目做了一些改动，现在项目已经开源，欢迎大佬一起做讨论
https://github.com/zhangnn520/my_sadtalker

https://github.com/OpenTalker/SadTalker/assets/58899025/2763ef34-a4cc-48b3-8ad9-25470b539c29

**Comment by xiao-keeplearning** [comment]
你的项目在原项目基础上加了什么改进？@zhangnn520

**Comment by zhangnn520** [comment]
> 你的项目在原项目基础上加了什么改进？@zhangnn520

没有什么改进

**Comment by 17719498724** [comment]
请问如何使用透明背景的人像图片,来生成webm格式的 数字人视频?
训练的模型支持处理透明背景的人像图片吗?
