### ISSUE TITLE
mp4文件切割失败

### ISSUE THREAD

**Issue by JackMa2023** [Winfredy/SadTalker#81]
描述：使用mp4文件作为输入时，会报错，是不支持mp4文件吗？
命令: 
python inference.py --driven_audio G:\SadTalker\test002\singer1.wav --source_image G:\SadTalker\test002\3.mp4 --result_dir G:\SadTalker\test002\ --still --preprocess full --enhancer gfpgan

报错信息：
3DMM Extraction for source image
Traceback (most recent call last):
  File "inference.py", line 160, in <module>
    main(args)
  File "inference.py", line 72, in main
    first_coeff_path, crop_pic_path, crop_info =  preprocess_model.generate(pic_path, first_frame_dir, args.preprocess)
  File "G:\BaiduNetdiskDownload\SadTalker\src\utils\preprocess.py", line 93, in generate
    x_full_frames, crop, quad = self.croper.crop(x_full_frames_before, still=True, xsize=pic_size)
TypeError: cannot unpack non-iterable NoneType object

**Comment by vinthony** [comment]
参考 #68

**Comment by JackMa2023** [comment]
mp4中的人物是真人，人脸清晰。

**Comment by vinthony** [comment]
在 #138 中fixed了
