### ISSUE TITLE
Installation Errors.

### ISSUE THREAD

**Issue by bbecausereasonss** [Winfredy/SadTalker#85]
These are the errors I get in auto's when the plugin attempts to install. Any help please?

-

C:\Users\xxxx\Deep\stable-diffusion-webui\venv\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Skipping broken symlink: C:\Users\xxxx\Deep\stable-diffusion-webui\models\Stable-diffusion\v2-1_512-ema-pruned.ckpt
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: C:\Users\xxxx\Deep\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
Loading Unprompted v7.9.1 by Therefore Games
(SETUP) Initializing Unprompted object...
(SETUP) Loading configuration files...
(SETUP) Debug mode is False
Loading weights [e1441589a6] from C:\Users\xxxx\Deep\stable-diffusion-webui\model.ckpt
Creating model from config: C:\Users\xxxx\Deep\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
face-alignment False
Installing requirements for SadTalker
imageio True
imageio-ffmpeg False
Installing requirements for SadTalker
librosa True
pydub True
scipy True
tqdm True
yacs True
pyyaml False
Installing requirements for SadTalker
dlib True
gfpgan True
download models for SadTalker
mkdir: cannot create directory ‘./checkpoints’: File exists
mkdir: cannot create directory ‘\r’: File exists
File ‘./checkpoints/auido2exp_00300-model.pth\r’ already there; not retrieving.
File ‘./checkpoints/auido2pose_00140-model.pth\r’ already there; not retrieving.
File ‘./checkpoints/epoch_20.pth\r’ already there; not retrieving.
File ‘./checkpoints/facevid2vid_00189-model.pth.tar\r’ already there; not retrieving.
File ‘./checkpoints/shape_predictor_68_face_landmarks.dat\r’ already there; not retrieving.
File ‘./checkpoints/wav2lip.pth\r’ already there; not retrieving.
File ‘./checkpoints/mapping_00229-model.pth.tar\r’ already there; not retrieving.
File ‘./checkpoints/BFM_Fitting.zip\r’ already there; not retrieving.
File ‘./checkpoints/hub.zip\r’ already there; not retrieving.
./scripts/download_models.sh: line 11: $'\r': command not found
./scripts/download_models.sh: line 12: unzip: command not found
./scripts/download_models.sh: line 13: unzip: command not found
Error executing callback ui_tabs_callback for C:\Users\xxxx\Deep\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py
Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py", line 62, in on_ui_tabs
    install()
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py", line 57, in install
    launch.run("cd " + paths.script_path+"/extensions/SadTalker && bash ./scripts/download_models.sh", live=True)
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\launch.py", line 81, in run
    raise RuntimeError(f"""{errdesc or 'Error running command'}.
RuntimeError: Error running command.
Command: cd C:\Users\xxxx\Deep\stable-diffusion-webui/extensions/SadTalker && bash ./scripts/download_models.sh
Error code: 127

**Comment by vinthony** [comment]
similar to #80 , the file name is not correct in windows.

**Comment by vinthony** [comment]
update the auto downloader, now it can be downloaded from huggingface

**Comment by bbecausereasonss** [comment]
> update the auto downloader, now it can be downloaded from huggingface

Sorry can you explain what you mean here? I'm still having the issue. What can be downloaded from huggingface and whats the link?

**Comment by vinthony** [comment]
all the checkpoints will be downloaded from hugginngface, which avoid using bash in our extension
