### ISSUE TITLE
Error - 'bash' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by dza6549** [Winfredy/SadTalker#87]
Hi

Thank you for releasing this code. I am using the Automatic1111 webui on Windows 10 and receive the following error when I open the webui after installation.

**'bash' is not recognized as an internal or external command,**

Please let me know if I can provide further information to assist in the resolution of this error.

Thank you

**Comment by vinthony** [comment]
refer: https://github.com/Winfredy/SadTalker/issues/78#issuecomment-1501074375

**Comment by vinthony** [comment]
update the auto downloader, now it can be downloaded from `huggingface`
