### ISSUE TITLE
希望大神光顾这个问题~

### ISSUE THREAD

**Issue by RAYaaaaaaaaaaaaa** [Winfredy/SadTalker#896]
显示出现图1的问题，然后我点击【launcher.py】这个选项，下载了很多东西，然后就成了图2，求指点，这是怎么了~
<img width="876" alt="企业微信截图_20240506121010" src="https://github.com/OpenTalker/SadTalker/assets/168402415/5d6fa715-764e-4508-969a-7a24bb3e64bc">
<img width="876" alt="企业微信截图_20240506144414" src="https://github.com/OpenTalker/SadTalker/assets/168402415/253f2c64-c79e-4a7b-ae30-012ef9abe41c">

**Comment by RAYaaaaaaaaaaaaa** [comment]
就在这定着不动了，求救！

**Comment by hanqingchina** [comment]
它在后台进行安装，别动他，会下载很多相关依赖，关键他不显示具体的工作进程，要么装成功，要么给你错误提示，这时候你就能看到他的具体工作信息

**Comment by RAYaaaaaaaaaaaaa** [comment]
感谢回复~   之前这个界面放着不动差不多一个小时都没反应我就给关了，可能是后台还在下东西吧，那我在等时间长一点看看！ 万分感谢！！ @hanqingchina

**Comment by RAYaaaaaaaaaaaaa** [comment]
啊啊啊啊啊啊变成这样了，救命
<img width="876" alt="企业微信截图_20240506180205" src="https://github.com/OpenTalker/SadTalker/assets/168402415/2c7b157d-7085-4bd6-a072-8d40239c2aa5">
@hanqingchina

**Comment by RAYaaaaaaaaaaaaa** [comment]
问题在持续发酵，我更新了python版本，pip更新到了24.0版本，但是还是错误，错误变成了如下所示~
<img width="584" alt="企业微信截图_20240507151315" src="https://github.com/OpenTalker/SadTalker/assets/168402415/4c3940f4-5510-4b49-b011-1869a9f5556b">
<img width="584" alt="企业微信截图_20240507151325" src="https://github.com/OpenTalker/SadTalker/assets/168402415/5f4854dc-a6e0-467f-bc90-23e8631f1989">

**Comment by RAYaaaaaaaaaaaaa** [comment]
我还下载了一个这玩意放在了【scripts】文件夹下，也没用~~  下方的报错是跑【launcher.py】时的报错
<img width="509" alt="企业微信截图_20240507152400" src="https://github.com/OpenTalker/SadTalker/assets/168402415/da30cc97-f346-47f4-a154-c4156bcfc630">
<img width="864" alt="企业微信截图_20240507151908" src="https://github.com/OpenTalker/SadTalker/assets/168402415/ab017465-d654-4629-aadd-6e13f6b93828">

**Comment by Seafood0808** [comment]
下載3.8.0版本Python手動安裝(如果你有其他需要使用3.12.3的版本就不要再安裝時加入path)，記好3.80安裝位置
將SadTalker_withRefVideo\venv目錄中的pyvenv.cfg文件用記事本打開，將路徑修改為3.8.0的路徑即可
![螢幕擷取畫面 2024-05-08 093648](https://github.com/OpenTalker/SadTalker/assets/97867558/b61c97ed-e607-4509-b3bc-55c63f4c6b86)

**Comment by RAYaaaaaaaaaaaaa** [comment]
@Seafood0808 蟹蟹！！果然【launcher.py】这里没问题了，只是跑bat的时候,有以下的报错了，应该python的地址没输错~　emmmm~我看【venv】这个文件夹里也是有【pyvenv.cfg】这个文件的拜托啦～
<img width="876" alt="企业微信截图_20240508171927" src="https://github.com/OpenTalker/SadTalker/assets/168402415/80f84eea-6a40-4559-bb37-870ba7c4981a">
<img width="371" alt="企业微信截图_20240508172129" src="https://github.com/OpenTalker/SadTalker/assets/168402415/0a64cd7f-33a0-4245-848e-330527beee06">
<img width="856" alt="企业微信截图_20240508172224" src="https://github.com/OpenTalker/SadTalker/assets/168402415/2675e9ee-ba3a-4b36-8a34-9b288bb6add9">
<img width="721" alt="企业微信截图_20240508173503" src="https://github.com/OpenTalker/SadTalker/assets/168402415/59c91721-7e92-4116-9581-3f4d819d398f">

**Comment by Seafood0808** [comment]
![image](https://github.com/OpenTalker/SadTalker/assets/97867558/98c823c6-477b-4a37-8d24-43159303c351)
你的"home =" 怎麼不見了

**Comment by RAYaaaaaaaaaaaaa** [comment]
哈哈哈哈，被我吃了，sorrysorry，黏贴的时候直接一起选中了~好了好了~~
然后又报错了~~~~~晕倒/(ㄒoㄒ)/~~

**Comment by Seafood0808** [comment]
> 哈哈哈哈，被我吃了，sorrysorry，黏贴的时候直接一起选中了~好了好了~~ 然后又报错了~~~~~晕倒/(ㄒoㄒ)/~~

跟上面一樣的錯誤?

conda activate sadtalker

pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url

torch==1.12.1 這個你裝了嗎?

**Comment by RAYaaaaaaaaaaaaa** [comment]
不是的，变了，原来帖子没被我关闭啊，上传图片的时候我以为被我错误关闭了，急得我。
这个在哪里看装没装啊~之前报这个错的时候下载了一个不知道该放在哪。
这个是现在的报错：
<img width="876" alt="企业微信截图_20240509091823" src="https://github.com/OpenTalker/SadTalker/assets/168402415/65c9ccbe-0213-4dd7-ac5b-3e1fa9cf7e1f">
这个是之前下载的我就直接拖着放在这个文件夹，但是好像没反应：
<img width="875" alt="企业微信截图_20240509092854" src="https://github.com/OpenTalker/SadTalker/assets/168402415/3d5e96a0-d543-4cd9-9b6f-03618d6e407f">

**Comment by Seafood0808** [comment]
在你的sadtalk根目錄 右鍵開啟終端 依下方順序序輸入 

conda create -n sadtalker python=3.8

conda activate sadtalker

pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index

conda install ffmpeg

pip install -r requirements.txt

**Comment by RAYaaaaaaaaaaaaa** [comment]
是不是我输入的不对。
<img width="584" alt="企业微信截图_20240509095711" src="https://github.com/OpenTalker/SadTalker/assets/168402415/4758b70f-d9b4-4cfe-8f80-226cdec4b536">

**Comment by Seafood0808** [comment]
改成重電腦左下角輸入CMD 開啟 從這裡讀sadtalk資料夾試試
cd SadTalker 

conda create -n sadtalker python=3.8

conda activate sadtalker

pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url 

conda install ffmpeg

pip install -r requirements.txt

**Comment by RAYaaaaaaaaaaaaa** [comment]
因为我是编程文盲，所以第一项【cd SadTalker】的时候，不知道您的意思是直接输入就行还是需要路径，我就把路径也试了一下。
emmmm  不知道我的操作对不对，这个样子了
<img width="876" alt="企业微信截图_20240509102740" src="https://github.com/OpenTalker/SadTalker/assets/168402415/978745b4-0c70-4540-9dad-a14c8bb85ef7">

**Comment by Seafood0808** [comment]
你要CD進你的 sadtalk資料夾 CD 你的 sadtalk 資料夾路徑

**Comment by Seafood0808** [comment]
![image](https://github.com/OpenTalker/SadTalker/assets/97867558/88159c47-b231-4c85-ba67-c46bc30788d5)

**Comment by Seafood0808** [comment]
如果還不對
https://www.anaconda.com/
這個官方要求的你有裝了嗎?

**Comment by RAYaaaaaaaaaaaaa** [comment]
这一行是cd的资料夹的路径
<img width="864" alt="企业微信截图_20240509104011" src="https://github.com/OpenTalker/SadTalker/assets/168402415/0bd8ee11-4a86-406f-8dfb-ca8cbd6c012c">
官方要求的没装过，装哪个呢？
<img width="1280" alt="企业微信截图_20240509104734" src="https://github.com/OpenTalker/SadTalker/assets/168402415/95308fb2-11a2-4e75-8159-38aee99ab66c">

**Comment by Seafood0808** [comment]
![image](https://github.com/OpenTalker/SadTalker/assets/97867558/beb3513e-8900-4c5d-a614-ca351a75e98a)
前面要空格先試試看

**Comment by RAYaaaaaaaaaaaaa** [comment]
我cd的路径对吗，会不会第一步我的操作就出问题了呀！
<img width="876" alt="企业微信截图_20240509113722" src="https://github.com/OpenTalker/SadTalker/assets/168402415/ff4d1a35-58d2-4184-b214-17a1d3664791">
<img width="1081" alt="企业微信截图_20240509113510" src="https://github.com/OpenTalker/SadTalker/assets/168402415/c00ec4c4-b9cd-499e-9b0e-ce2a746783f2">

**Comment by Seafood0808** [comment]
建議你分開安裝因為sadtalk 使用的py與torch 版本不一樣

**Comment by RAYaaaaaaaaaaaaa** [comment]
emmmm~分开安装python和什么啊 ？你说的这个官方安装的这个我没安装过，点进去找不到安装的东西。
<img width="1189" alt="企业微信截图_20240509121155" src="https://github.com/OpenTalker/SadTalker/assets/168402415/e4e4d3d1-8e1b-4323-a6c8-4766a5f99cb3">

**Comment by Seafood0808** [comment]
你先去檢查一下主頁面所要求的軟體再繼續安裝
直接照著安裝步驟走

**Comment by RAYaaaaaaaaaaaaa** [comment]
上边写的我貌似都按了，还看了b站两个视频https://www.bilibili.com/video/BV1BL411h7ie/?spm_id_from=333.880.my_history.page.click&vd_source=baacfc8f4afc2680e57ea05f60d3c55e
https://www.bilibili.com/video/BV15V4y1b7HQ/?spm_id_from=333.880.top_right_bar_window_history.content.click
让按的都装了/(ㄒoㄒ)/~~哭啊

**Comment by Seafood0808** [comment]
這麼說好了，你看sadtalk這個專案為何會有這麼多問題報錯，說明這個專案本身就有點問題，這些問題雖然不是不能解決，但自身也要有一定的除錯能力，會用到conda虛擬環境一定有他的理由，你上面給的兩個軟體都沒有安裝conda，你先尋找如何安裝conda之後我們在解決接下來的問題。

**Comment by RAYaaaaaaaaaaaaa** [comment]
嗯嗯，好，那我先研究一下怎么安装conda，看看能不能解决。我也是看说这个sadtalker问题好多

**Comment by RAYaaaaaaaaaaaaa** [comment]
@Seafood0808 问题解决了  python版本使用的3.8.1   高版本不行但是3.80版本又低了也不行   然后出现了这个报错【AttributeError: 'Row' object has no attribute 'style'】
然后在这个帖子里找到了解决办法【https://github.com/OpenTalker/SadTalker/issues/693】更换了原来下载包里的这个文件
[app_sadtalker.zip](https://github.com/user-attachments/files/16577101/app_sadtalker.zip)就可以跑了！
谢谢您之前的耐心解答!!!!!!
