### ISSUE TITLE
Keep getting this error

### ISSUE THREAD

**Issue by bbecausereasonss** [Winfredy/SadTalker#9]
Traceback (most recent call last):
  File "inference.py", line 9, in <module>
    from generate_batch import get_data
  File "C:\Users\chlyw\Desktop\SadTalker\generate_batch.py", line 5, in <module>
    import librosa
  File "C:\Users\chlyw\.conda\envs\sadtalker\lib\site-packages\librosa\__init__.py", line 12, in <module>
    from . import core
  File "C:\Users\chlyw\.conda\envs\sadtalker\lib\site-packages\librosa\core\__init__.py", line 102, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "C:\Users\chlyw\.conda\envs\sadtalker\lib\site-packages\librosa\core\time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\chlyw\.conda\envs\sadtalker\lib\site-packages\librosa\util\__init__.py", line 67, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Users\chlyw\.conda\envs\sadtalker\lib\site-packages\librosa\util\utils.py", line 111, in <module>
    def valid_audio(y, mono=True):
  File "C:\Users\chlyw\.conda\envs\sadtalker\lib\site-packages\librosa\cache.py", line 49, in wrapper
    if self.cachedir is not None and self.level >= level:
AttributeError: 'CacheManager' object has no attribute 'cachedir'

**Comment by Aghneel** [comment]
Make sure you're on python 3.8.0 and try to run this` pip install librosa -U` or follow https://github.com/Winfredy/SadTalker/issues/4#issuecomment-1459279839 worked for me

**Comment by bbecausereasonss** [comment]
Still getting this bloody error. I've tried so many things now, re-created the environment a billion times. Downloaded openssl set environment variables. Same error.

**Comment by bbecausereasonss** [comment]
My ChatGPT log. Nothing works constant OpenSSL errors.

https://www.dropbox.com/s/6x2vcneum8zaaje/SSLissues.pdf?dl=0

**Comment by bbecausereasonss** [comment]
OMG FINALLY. Random article worked.


copy libcrypto-1_1-x64.* and libssl-1_1-x64.* from anaconda3>library>bin to ananconda3>dlls

**Comment by bbecausereasonss** [comment]
Now I cannot seem to install pytorch with cuda, no matter what I try.

**Comment by bbecausereasonss** [comment]
Okay solved that problem now I'm getting another lol.

"(sadtalker) C:\Users\chlyw\Desktop\SadTalker>python inference.py --driven_audio Carlin.wav --source_image Carlin.png --result_dir \
checkpoints\epoch_20.pth
checkpoints\auido2pose_00140-model.pth
checkpoints\auido2exp_00300-model.pth
checkpoints\facevid2vid_00189-model.pth.tar
checkpoints\mapping_00229-model.pth.tar
landmark Det:: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:06<00:00,  6.80s/it]
 3DMM Extraction In Video:: 100%|████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.47it/s]
Traceback (most recent call last):
  File "inference.py", line 98, in <module>
    main(args)
  File "inference.py", line 70, in main
    batch = get_data(first_coeff_path, audio_path, device)
  File "C:\Users\chlyw\Desktop\SadTalker\generate_batch.py", line 71, in get_data
    orig_mel = audio.melspectrogram(wav).T
  File "C:\Users\chlyw\Desktop\SadTalker\audio.py", line 47, in melspectrogram
    S = _amp_to_db(_linear_to_mel(np.abs(D))) - hp.ref_level_db
  File "C:\Users\chlyw\Desktop\SadTalker\audio.py", line 95, in _linear_to_mel
    _mel_basis = _build_mel_basis()
  File "C:\Users\chlyw\Desktop\SadTalker\audio.py", line 100, in _build_mel_basis
    return librosa.filters.mel(hp.sample_rate, hp.n_fft, n_mels=hp.num_mels,
TypeError: mel() takes 0 positional arguments but 2 positional arguments (and 3 keyword-only arguments) were given"

**Comment by vinthony** [comment]
> mel() takes 0 positional arguments but 2 positional arguments (and 3 keyword-only arguments) were given

sorry about the initialization problems you have, we have already tested them on our machine, however, the real things are complicated.

this error occurs since librosa is in the wrong version, maybe you can try:

```
pip uninstall librosa -U
pip install librosa==0.7.1

```

**Comment by Aghneel** [comment]
> Hmm. Now I get this... I think I'm just going to wait until it is an Automatic1111 extension. Thanks for trying to help.
> 
> "(sadtalker) C:\Users\chlyw\Desktop\SadTalker>python inference.py --driven_audio Carlin.wav --source_image Carlin.png --result_dir Carlin.mp4 --camera_yaw -20 30 10 Traceback (most recent call last): File "inference.py", line 9, in from generate_batch import get_data File "C:\Users\chlyw\Desktop\SadTalker\generate_batch.py", line 5, in import librosa File "C:\Users\chlyw\anaconda3\envs\sadtalker\lib\site-packages\librosa__init__.py", line 12, in from . import core File "C:\Users\chlyw\anaconda3\envs\sadtalker\lib\site-packages\librosa\core__init__.py", line 123, in from .time_frequency import * # pylint: disable=wildcard-import File "C:\Users\chlyw\anaconda3\envs\sadtalker\lib\site-packages\librosa\core\time_frequency.py", line 11, in from ..util.exceptions import ParameterError File "C:\Users\chlyw\anaconda3\envs\sadtalker\lib\site-packages\librosa\util__init__.py", line 77, in from .utils import * # pylint: disable=wildcard-import File "C:\Users\chlyw\anaconda3\envs\sadtalker\lib\site-packages\librosa\util\utils.py", line 15, in from .decorators import deprecated File "C:\Users\chlyw\anaconda3\envs\sadtalker\lib\site-packages\librosa\util\decorators.py", line 9, in from numba.decorators import jit as optional_jit ModuleNotFoundError: No module named 'numba.decorators'"

Did you follow what the guy in the comment said you have to install these three
pip install librosa==0.7.2
pip install numba==0.48.0
pip install llvmlite==0.31.0

**Comment by vinthony** [comment]
I am glad you made it out!

you may try to enhance the results frame-wisely through GFPGAN https://github.com/TencentARC/GFPGAN

**Comment by zwyzjj** [comment]
> 

My Python version is 3.9, and I cannot install numba version 0.48.0. Does this AI have to be 0.48.0 to run properly?
