### ISSUE TITLE
视频生成过程中发生错误：' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by smartOf360** [Winfredy/SadTalker#96]
system: win10 

Package                 Version
----------------------- ---------------
absl-py                 1.4.0
addict                  2.4.0
aiofiles                23.1.0
aiohttp                 3.8.4
aiosignal               1.3.1
altair                  4.2.2
anyio                   3.6.2
async-timeout           4.0.2
attrs                   22.2.0
audioread               3.0.0
basicsr                 1.4.2
cachetools              5.3.0
certifi                 2022.12.7
cffi                    1.15.1
charset-normalizer      2.1.1
click                   8.1.3
colorama                0.4.6
contourpy               1.0.7
cycler                  0.11.0
decorator               5.1.1
dlib-bin                19.24.1
entrypoints             0.4
face-alignment          1.3.5
facexlib                0.2.5
fastapi                 0.95.0
ffmpy                   0.3.0
filelock                3.9.0
filterpy                1.4.5
fonttools               4.39.3
frozenlist              1.3.3
fsspec                  2023.4.0
future                  0.18.3
gfpgan                  1.3.8
google-auth             2.17.2
google-auth-oauthlib    1.0.0
gradio                  3.24.1
gradio_client           0.0.8
grpcio                  1.53.0
h11                     0.14.0
httpcore                0.16.3
httpx                   0.23.3
huggingface-hub         0.13.4
idna                    3.4
imageio                 2.19.3
imageio-ffmpeg          0.4.7
importlib-metadata      6.3.0
importlib-resources     5.12.0
Jinja2                  3.1.2
joblib                  1.1.0
jsonschema              4.17.3
kiwisolver              1.4.4
kornia                  0.6.8
librosa                 0.9.2
linkify-it-py           2.0.0
llvmlite                0.39.1
lmdb                    1.4.1
Markdown                3.4.3
markdown-it-py          2.2.0
MarkupSafe              2.1.2
matplotlib              3.7.1
mdit-py-plugins         0.3.3
mdurl                   0.1.2
mpmath                  1.2.1
multidict               6.0.4
networkx                3.0
numba                   0.56.4
numpy                   1.23.4
oauthlib                3.2.2
opencv-python           4.7.0.72
orjson                  3.8.10
packaging               23.0
pandas                  2.0.0
Pillow                  9.3.0
pip                     23.0.1
pkgutil_resolve_name    1.3.10
platformdirs            3.2.0
pooch                   1.7.0
protobuf                4.22.1
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycparser               2.21
pydantic                1.10.7
pydub                   0.25.1
pyparsing               3.0.9
pyrsistent              0.19.3
python-dateutil         2.8.2
python-multipart        0.0.6
pytz                    2023.3
PyWavelets              1.4.1
PyYAML                  6.0
requests                2.28.1
requests-oauthlib       1.3.1
resampy                 0.3.1
rfc3986                 1.5.0
rsa                     4.9
scikit-image            0.19.3
scikit-learn            1.1.3
scipy                   1.5.3
semantic-version        2.10.0
setuptools              65.6.3
six                     1.16.0
sniffio                 1.3.0
soundfile               0.12.1
starlette               0.26.1
sympy                   1.11.1
tb-nightly              2.13.0a20230409
tensorboard-data-server 0.7.0
tensorboard-plugin-wit  1.8.1
threadpoolctl           3.1.0
tifffile                2023.3.21
toolz                   0.12.0
torch                   2.0.0+cu118
torchaudio              2.0.1+cu118
torchvision             0.15.1+cu118
tqdm                    4.65.0
trimesh                 3.9.20
typing_extensions       4.4.0
tzdata                  2023.3
uc-micro-py             1.0.1
urllib3                 1.26.13
uvicorn                 0.21.1
websockets              11.0.1
Werkzeug                2.2.3
wheel                   0.38.4
wincertstore            0.2
yacs                    0.1.8
yapf                    0.32.0
yarl                    1.8.2
zipp                    3.15.0

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '0af1a84c-f6b5-4d9d-b2f0-320cd4e20619.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:21.66, start: 0.000000, bitrate: 805 kb/s
    Stream #0:0(und): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 768x768 [SAR 1:1 DAR 1:1], 727 kb/s, 25 fps, 25 tbr, 12800 tbn, 25 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 76 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
./docs/sadtalker_log.png: No such file or directory
The generated video is named D:\audia2face\out\2023_04_10_18.27.46/ruixuan-001##ruixuan-001_full.mp4
face enhancer....
Face Enhancer::   0%|                                                                                                                                                   | 0/71 [00:00<?, ?it/s][ WARN:0@93.068] global loadsave.cpp:244 cv::findDecoder imread_('D'): can't open/read file: check file path/integrity
Face Enhancer::   0%|                                                                                                                                                   | 0/71 [00:00<?, ?it/s] 
Traceback (most recent call last):
  File "inference.py", line 158, in <module>
    main(args)
  File "inference.py", line 112, in main
    animate_from_coeff.generate(data, save_dir, pic_path, crop_info, \
  File "D:\src\SadTalker\src\facerender\animate.py", line 202, in generate
    enhanced_images = face_enhancer(full_video_path, method=enhancer, bg_upsampler=background_enhancer)
  File "D:\src\SadTalker\src\utils\face_enhancer.py", line 81, in enhancer
    cropped_faces, restored_faces, r_img = restorer.enhance(
  File "C:\Users\liugang\.conda\envs\sadtalker\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\liugang\.conda\envs\sadtalker\lib\site-packages\gfpgan\utils.py", line 109, in enhance
    self.face_helper.read_image(img)
  File "C:\Users\liugang\.conda\envs\sadtalker\lib\site-packages\facexlib\utils\face_restoration_helper.py", line 114, in read_image
    if np.max(img) > 256:  # 16-bit image
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by vinthony** [comment]
尝试更新代码，已经修复了

**Comment by smartOf360** [comment]
更新之后，还是不行，我把videoio.py的save_video_with_watermark函数先修改了一下，将watermark为Ture的代码注释掉就OK了。

**Comment by vinthony** [comment]
fixed. 路径那里有个typo
