### ISSUE TITLE
WEBUI中安装不上

### ISSUE THREAD

**Issue by paulzhang913** [Winfredy/SadTalker#99]
GitCommandError: Cmd('git') failed due to: exit code(128) cmdline: git clone -v -- https://github.com/Winfredy/SadTalker C:\softz\tmp\SadTalker stderr: 'Cloning into 'C:\softz\tmp\SadTalker'... fatal: unable to access 'https://github.com/Winfredy/SadTalker/': Failed to connect to github.com port 443 after 21147 ms: Timed out '

**Comment by wizd** [comment]
看log是翻墙失败

**Comment by paulzhang913** [comment]
> 

需要翻墙吗？

**Comment by paulzhang913** [comment]
GitCommandError: Cmd('git') failed due to: exit code(128) cmdline: git clone -v -- https://github.com/Winfredy/SadTalker C:\softz\tmp\SadTalker stderr: 'Cloning into 'C:\softz\tmp\SadTalker'... fatal: unable to access 'https://github.com/Winfredy/SadTalker/': OpenSSL SSL_read: Connection was reset, errno 10054 '

**Comment by vinthony** [comment]
网络问题，可能需要一些魔法。
